import type { PracticeContext } from "@/types/conversation";

export type PhraseRule = {
  vietnamese: string;
  english: string;
};

export type KeywordIntentRule = {
  intent: string;
  keywords: string[];
  english: string;
  sample: string;
  blockedKeywords?: string[];
};

export const phraseRules: Record<PracticeContext, PhraseRule[]> = {
  home: [
    { vietnamese: "con muon uong nuoc", english: "Can I have some water, please?" },
    { vietnamese: "con khat nuoc", english: "I'm thirsty." },
    { vietnamese: "cho con xin nuoc", english: "Can I have some water, please?" },
    { vietnamese: "con doi bung", english: "I'm hungry." },
    { vietnamese: "con doi", english: "I'm hungry." },
    { vietnamese: "con muon an com", english: "I want to eat." },
    { vietnamese: "con muon an banh", english: "I want to eat a snack." },
    { vietnamese: "con muon an toi", english: "I want to eat dinner." },
    { vietnamese: "con muon an sang", english: "I want to eat breakfast." },
    { vietnamese: "con muon an trai cay", english: "I want some fruit." },
    { vietnamese: "con muon an kem", english: "I want some ice cream." },
    { vietnamese: "con muon an", english: "I want to eat." },
    { vietnamese: "con muon keo", english: "I want some candy." },
    { vietnamese: "con muon uong sua", english: "Can I have some milk, please?" },
    { vietnamese: "con no roi", english: "I'm full." },
    { vietnamese: "con dau bung", english: "My stomach hurts." },
    { vietnamese: "con dau dau", english: "My head hurts." },
    { vietnamese: "con bi dau", english: "I got hurt." },
    { vietnamese: "con bi om", english: "I'm sick." },
    { vietnamese: "con muon uong thuoc", english: "I need to take medicine." },
    { vietnamese: "con buon ngu", english: "I'm sleepy." },
    { vietnamese: "con muon di ngu", english: "I want to sleep." },
    { vietnamese: "con muon di ve sinh", english: "I need to go to the bathroom." },
    { vietnamese: "con muon di tam", english: "I want to take a bath." },
    { vietnamese: "con muon rua tay", english: "I want to wash my hands." },
    { vietnamese: "con muon choi", english: "I want to play." },
    { vietnamese: "con muon di choi cong vien", english: "I want to go to the park." },
    { vietnamese: "con muon di choi", english: "I want to go out and play." },
    { vietnamese: "con muon bo choi voi con", english: "Dad, please play with me." },
    { vietnamese: "con muon me doc truyen cho con", english: "Mom, please read me a story." },
    { vietnamese: "con muon xem phim hoat hinh", english: "I want to watch cartoons." },
    { vietnamese: "con muon dung gan cua so", english: "I want to stand near the window." },
    { vietnamese: "con muon mo cua so", english: "I want to open the window." },
    { vietnamese: "con muon nhin buc tuong kia", english: "I want to see that statue." },
    { vietnamese: "con muon xem con ca mau vang kia", english: "I want to see that yellow fish." },
    { vietnamese: "con muon nhin con ca mau vang kia", english: "I want to see that yellow fish." },
    { vietnamese: "me chup cho con voi buc tuong kia", english: "Mom, please take a picture of me with that statue." },
    { vietnamese: "chup cho con voi buc tuong kia", english: "Mom, please take a picture of me with that statue." },
    { vietnamese: "con muon nhin cai may bay tren troi", english: "I want to see the airplane in the sky." },
    { vietnamese: "con muon nhin may bay tren troi", english: "I want to see the airplane in the sky." },
    { vietnamese: "con thay may bay tren troi", english: "I see an airplane in the sky." },
    { vietnamese: "me oi minh co the di thang may duoc khong", english: "Can we take the elevator?" },
    { vietnamese: "minh co the di thang may duoc khong", english: "Can we take the elevator?" },
    { vietnamese: "con muon di thang may", english: "I want to take the elevator." },
    { vietnamese: "me oi sao troi toi nhanh vay", english: "Mom, why does it get dark so fast?" },
    { vietnamese: "sao troi toi nhanh vay", english: "Mom, why does it get dark so fast?" },
    { vietnamese: "con lam roi roi", english: "I dropped it." },
    { vietnamese: "con lam roi nuoc", english: "I spilled water." },
    { vietnamese: "con khong thich cai nay", english: "I don't like this." },
    { vietnamese: "con thich cai nay", english: "I like this." },
    { vietnamese: "cai kia do me", english: "That one, Mom." },
    { vietnamese: "con muon cai nay cai kia", english: "I want this one and that one." },
    { vietnamese: "con muon cai nay", english: "I want this one." },
    { vietnamese: "con muon cai kia", english: "I want that one." },
    { vietnamese: "giup con voi", english: "Can you help me, please?" },
    { vietnamese: "con can om", english: "I need a hug." },
    { vietnamese: "con so", english: "I'm scared." },
    { vietnamese: "con muon thay quan ao", english: "I want to change my clothes." },
    { vietnamese: "con khong tu mac duoc", english: "I need help getting dressed." },
    { vietnamese: "cai ao nay chat qua", english: "This shirt is too tight." },
    { vietnamese: "con nong qua", english: "I'm too hot." },
    { vietnamese: "con lanh qua", english: "I'm too cold." },
    { vietnamese: "bat den giup con", english: "Please turn on the light." },
    { vietnamese: "tat den giup con", english: "Please turn off the light." },
    { vietnamese: "con muon nghe nhac", english: "I want to listen to music." },
    { vietnamese: "con muon ve tranh", english: "I want to draw a picture." },
    { vietnamese: "con muon choi xep hinh", english: "I want to play with building blocks." },
    { vietnamese: "con muon choi bup be", english: "I want to play with my doll." },
    { vietnamese: "con muon choi o to", english: "I want to play with my toy car." },
    { vietnamese: "con muon xem sach", english: "I want to look at a book." },
    { vietnamese: "con muon goi dien cho bo", english: "I want to call Dad." },
    { vietnamese: "con nho bo", english: "I miss Dad." },
    { vietnamese: "con nho me", english: "I miss Mom." },
    { vietnamese: "con buon", english: "I'm sad." },
    { vietnamese: "con vui lam", english: "I'm very happy." },
    { vietnamese: "con dang gian", english: "I'm angry." },
    { vietnamese: "con khong thoai mai", english: "I don't feel comfortable." },
    { vietnamese: "con can nghi ngoi", english: "I need to rest." },
    { vietnamese: "con can khan giay", english: "I need a tissue, please." },
    { vietnamese: "con muon xi mui", english: "I need to blow my nose." },
    { vietnamese: "con bi ho", english: "I have a cough." },
    { vietnamese: "con bi sot", english: "I have a fever." },
    { vietnamese: "con bi ngua", english: "I feel itchy." },
    { vietnamese: "con muon danh rang", english: "I want to brush my teeth." },
    { vietnamese: "con muon chai toc", english: "I want to brush my hair." },
    { vietnamese: "con muon don do choi", english: "I want to put my toys away." },
    { vietnamese: "con se tu don", english: "I will clean it up myself." },
    { vietnamese: "con lam vo cai nay", english: "I broke this." },
    { vietnamese: "con xin loi", english: "I'm sorry." },
    { vietnamese: "con cam on me", english: "Thank you, Mom." },
    { vietnamese: "cho con them nam phut", english: "Can I have five more minutes?" },
    { vietnamese: "con can yen tinh mot chut", english: "I need some quiet time." },
    { vietnamese: "con muon choi dien thoai", english: "I want to play on the phone." },
    { vietnamese: "con muon ra ngoai choi", english: "I want to go outside and play." },
    { vietnamese: "con muon di choi voi me", english: "I want to go out with Mom." },
    { vietnamese: "con khong thich mon nay", english: "I don't like this food." },
    { vietnamese: "con muon nghi ngoi mot chut", english: "I want to rest for a moment." },
  ],
  school: [
    { vietnamese: "con can but chi", english: "I need a pencil, please." },
    { vietnamese: "con can but", english: "I need a pencil, please." },
    { vietnamese: "con bi mat but", english: "I lost my pencil." },
    { vietnamese: "con can cuc tay", english: "I need an eraser, please." },
    { vietnamese: "con quen sach", english: "I forgot my book." },
    { vietnamese: "con quen vo", english: "I forgot my notebook." },
    { vietnamese: "con khong tim thay sach", english: "I can't find my book." },
    { vietnamese: "con khong hieu bai", english: "I don't understand the lesson." },
    { vietnamese: "con khong hieu", english: "I don't understand." },
    { vietnamese: "co the giup con khong", english: "Can you help me, please?" },
    { vietnamese: "co oi con can giup do", english: "Teacher, I need help, please." },
    { vietnamese: "con muon hoi co", english: "I want to ask the teacher." },
    { vietnamese: "con can di gap co", english: "I need to see the teacher." },
    { vietnamese: "con lam xong roi", english: "I'm finished." },
    { vietnamese: "con chua lam xong", english: "I'm not finished yet." },
    { vietnamese: "con khong lam duoc", english: "I can't do it yet." },
    { vietnamese: "con muon doc lai", english: "Can I read it again?" },
    { vietnamese: "con muon viet lai", english: "Can I write it again?" },
    { vietnamese: "con muon di ve sinh", english: "I need to go to the bathroom." },
    { vietnamese: "con can di lay nuoc", english: "I need to get water." },
    { vietnamese: "con muon uong nuoc", english: "Can I have some water, please?" },
    { vietnamese: "con muon ve nha", english: "I want to go home." },
    { vietnamese: "con bi dau dau", english: "My head hurts." },
    { vietnamese: "con bi dau bung", english: "My stomach hurts." },
    { vietnamese: "con bi dau", english: "I got hurt." },
    { vietnamese: "ban lay do cua con", english: "My friend took my thing." },
    { vietnamese: "ban day con", english: "My friend pushed me." },
    { vietnamese: "con bi ban day", english: "My friend pushed me." },
    { vietnamese: "ban khong cho con choi", english: "My friend won't let me play." },
    { vietnamese: "con khong nghe ro", english: "I can't hear clearly." },
    { vietnamese: "con can them thoi gian", english: "I need more time." },
    { vietnamese: "con muon doi cho ngoi", english: "Can I change seats, please?" },
    { vietnamese: "con muon nghi mot chut", english: "I need a short break." },
    { vietnamese: "con muon choi voi ban", english: "I want to play with my friend." },
    { vietnamese: "con muon di choi cong vien", english: "I want to go to the park." },
    { vietnamese: "con so co", english: "I'm scared, teacher." },
    { vietnamese: "cho con muon but chi", english: "Can I borrow a pencil, please?" },
    { vietnamese: "con can got but chi", english: "I need to sharpen my pencil." },
    { vietnamese: "con can mot to giay", english: "I need a sheet of paper, please." },
    { vietnamese: "con can thuoc ke", english: "I need a ruler, please." },
    { vietnamese: "con can keo", english: "I need scissors, please." },
    { vietnamese: "con can ho dan", english: "I need some glue, please." },
    { vietnamese: "con can but mau", english: "I need colored pencils, please." },
    { vietnamese: "con muon xuong phong y te", english: "I need to go to the nurse." },
    { vietnamese: "con thay chong mat", english: "I feel dizzy." },
    { vietnamese: "con thay nong va met", english: "I feel hot and tired." },
    { vietnamese: "con bi ho o lop", english: "I have a cough." },
    { vietnamese: "con can khan giay", english: "I need a tissue, please." },
    { vietnamese: "con khong mo duoc hop com", english: "I can't open my lunch box." },
    { vietnamese: "con quen mang do an trua", english: "I forgot my lunch." },
    { vietnamese: "con doi bung roi", english: "I'm hungry." },
    { vietnamese: "con co mot cau hoi", english: "I have a question." },
    { vietnamese: "co noi lai duoc khong", english: "Can you say that again, please?" },
    { vietnamese: "co noi cham lai duoc khong", english: "Can you speak more slowly, please?" },
    { vietnamese: "co noi to hon duoc khong", english: "Can you speak louder, please?" },
    { vietnamese: "con muon tra loi", english: "I want to answer." },
    { vietnamese: "den luot con chua", english: "Is it my turn yet?" },
    { vietnamese: "con chua co ban cung nhom", english: "I don't have a partner yet." },
    { vietnamese: "con choi cung duoc khong", english: "Can I play with you?" },
    { vietnamese: "ban dang treu con", english: "My friend is teasing me." },
    { vietnamese: "ban danh con", english: "My friend hit me." },
    { vietnamese: "con va ban dang cai nhau", english: "My friend and I are arguing." },
    { vietnamese: "con can cho yen tinh", english: "I need a quiet place." },
    { vietnamese: "o day on qua", english: "It's too noisy here." },
    { vietnamese: "con khong tim thay ba lo", english: "I can't find my backpack." },
    { vietnamese: "con di nham lop", english: "I went to the wrong classroom." },
    { vietnamese: "bao gio me don con", english: "When will Mom pick me up?" },
    { vietnamese: "con can goi cho me", english: "I need to call Mom." },
    { vietnamese: "con khong buoc duoc day giay", english: "I need help tying my shoelaces." },
    { vietnamese: "con khong keo duoc khoa ao", english: "I need help with my zipper." },
    { vietnamese: "con lam do nuoc ra ban", english: "I spilled water on the table." },
    { vietnamese: "con bi mac cuc tay", english: "I lost my eraser." },
    { vietnamese: "con bi mac cuc gom", english: "I lost my eraser." },
    { vietnamese: "co muon di so thu", english: "I want to go to the zoo." },
    { vietnamese: "co may gap co giao", english: "I want to see the teacher." },
    { vietnamese: "day la giao vien cua con", english: "This is my teacher." },
    { vietnamese: "day la giao vien cua toi", english: "This is my teacher." },
    { vietnamese: "con chua co nhom", english: "I don't have a group yet." },
    { vietnamese: "ban treu con", english: "My friend is teasing me." },
    { vietnamese: "bao gio me cua con den don", english: "When will my mom pick me up?" },
    { vietnamese: "con can khanh gai", english: "I need a tissue, please." },
  ],
  outside: [
    { vietnamese: "hom nay di choi gi vay", english: "Where are we going today?" },
    { vietnamese: "hom nay minh di dau", english: "Where are we going today?" },
    { vietnamese: "hom nay minh an gi", english: "What are we eating today?" },
    { vietnamese: "me oi cai kia la gi", english: "Mom, what is that?" },
    { vietnamese: "con muon di choi cong vien", english: "I want to go to the park." },
    { vietnamese: "con muon di choi", english: "I want to go out and play." },
    { vietnamese: "con muon ve nha", english: "I want to go home." },
    { vietnamese: "con muon di ve sinh", english: "I need to go to the bathroom." },
    { vietnamese: "con bi lac", english: "I'm lost. I need help." },
    { vietnamese: "con can giup do", english: "I need help, please." },
    { vietnamese: "con muon mua cai nay", english: "Can we buy this?" },
    { vietnamese: "con muon xem cai nay", english: "I want to see this." },
    { vietnamese: "con muon xem con robot", english: "I want to see the robot." },
    { vietnamese: "xem con robot", english: "I want to see the robot." },
    { vietnamese: "con muon xem con ca mau vang kia", english: "I want to see that yellow fish." },
    { vietnamese: "con muon nhin con ca mau vang kia", english: "I want to see that yellow fish." },
    { vietnamese: "con muon nhin cai may bay tren troi", english: "I want to see the airplane in the sky." },
    { vietnamese: "con muon nhin may bay tren troi", english: "I want to see the airplane in the sky." },
    { vietnamese: "con thay may bay tren troi", english: "I see an airplane in the sky." },
    { vietnamese: "con muon nhin buc tuong kia", english: "I want to see that statue." },
    { vietnamese: "me chup cho con voi buc tuong kia", english: "Mom, please take a picture of me with that statue." },
    { vietnamese: "chup cho con voi buc tuong kia", english: "Mom, please take a picture of me with that statue." },
    { vietnamese: "me oi minh co the di thang may duoc khong", english: "Can we take the elevator?" },
    { vietnamese: "minh co the di thang may duoc khong", english: "Can we take the elevator?" },
    { vietnamese: "con muon di thang may", english: "I want to take the elevator." },
    { vietnamese: "con muon dung gan cua so", english: "I want to stand near the window." },
    { vietnamese: "me oi sao troi toi nhanh vay", english: "Mom, why does it get dark so fast?" },
    { vietnamese: "sao troi toi nhanh vay", english: "Mom, why does it get dark so fast?" },
    { vietnamese: "con muon choi cai nay", english: "I want to play with this." },
    { vietnamese: "con muon chup anh", english: "I want to take a picture." },
    { vietnamese: "chup anh me oi", english: "I want to take a picture." },
    { vietnamese: "con khong thay me", english: "I can't see Mom." },
    { vietnamese: "cho con voi", english: "Please wait for me." },
    { vietnamese: "con khat nuoc", english: "I'm thirsty." },
    { vietnamese: "con doi bung", english: "I'm hungry." },
    { vietnamese: "con dau bung", english: "My stomach hurts." },
    { vietnamese: "con met roi", english: "I'm tired." },
    { vietnamese: "dong nguoi qua con so", english: "There are too many people. I'm scared." },
    { vietnamese: "con muon di cong vien nuoc", english: "Can we go to the water park?" },
    { vietnamese: "di cong vien nuoc", english: "Can we go to the water park?" },
    { vietnamese: "cho con di cong vien", english: "Can we go to the park?" },
    { vietnamese: "con muon cai nay", english: "I want this one." },
    { vietnamese: "con muon cai kia", english: "I want that one." },
    { vietnamese: "cai kia do me", english: "That one, Mom." },
    { vietnamese: "con muon an kem", english: "I want some ice cream." },
    { vietnamese: "me nam tay con nhe", english: "Mom, please hold my hand." },
    { vietnamese: "doi con voi", english: "Please wait for me." },
    { vietnamese: "di cham lai nhe", english: "Please walk more slowly." },
    { vietnamese: "con muon qua duong", english: "I want to cross the street." },
    { vietnamese: "den xanh chua me", english: "Is the light green yet, Mom?" },
    { vietnamese: "co xe dang toi", english: "A car is coming." },
    { vietnamese: "con can deo khau trang", english: "I need to wear my mask." },
    { vietnamese: "con can boi kem chong nang", english: "I need sunscreen." },
    { vietnamese: "con can doi mu", english: "I need to wear my hat." },
    { vietnamese: "troi mua roi", english: "It's raining." },
    { vietnamese: "con can cay o", english: "I need an umbrella." },
    { vietnamese: "con muon vao nha hang", english: "I want to go to a restaurant." },
    { vietnamese: "cho con xem thuc don", english: "Can I see the menu, please?" },
    { vietnamese: "con khong an cay", english: "I can't eat spicy food." },
    { vietnamese: "con bi di ung dau phong", english: "I'm allergic to peanuts." },
    { vietnamese: "nha ve sinh o dau", english: "Where is the bathroom?" },
    { vietnamese: "con muon ngoi ghe", english: "I want to sit on the bench." },
    { vietnamese: "minh nghi mot chut nhe", english: "Can we rest for a moment?" },
    { vietnamese: "con met khong di noi nua", english: "I'm too tired to keep walking." },
    { vietnamese: "minh can mua ve", english: "We need to buy tickets." },
    { vietnamese: "minh xep hang o dau", english: "Where should we line up?" },
    { vietnamese: "o day to qua", english: "It's too loud here." },
    { vietnamese: "o day sang qua", english: "It's too bright here." },
    { vietnamese: "con so con cho kia", english: "I'm scared of that dog." },
    { vietnamese: "con muon xem cac con vat", english: "I want to see the animals." },
    { vietnamese: "con co duoc cho con vat an khong", english: "Can I feed the animal?" },
    { vietnamese: "con khong muon cham vao no", english: "I don't want to touch it." },
    { vietnamese: "con muon vao san choi", english: "I want to go to the playground." },
    { vietnamese: "con muon choi xich du", english: "I want to play on the swing." },
    { vietnamese: "con muon choi cau truot", english: "I want to go down the slide." },
    { vietnamese: "con muon choi bong", english: "I want to play with the ball." },
    { vietnamese: "minh di xe buyt nhe", english: "Can we take the bus?" },
    { vietnamese: "minh goi taxi nhe", english: "Can we take a taxi?" },
    { vietnamese: "dung o day nhe", english: "Please stop here." },
    { vietnamese: "con bi lac goi cho me giup con", english: "I'm lost. Please call my mom." },
    { vietnamese: "con nhin thay may bay tren troi", english: "I see an airplane in the sky." },
    { vietnamese: "con nhin thay may bay tren troi kia", english: "I see an airplane in the sky." },
  ],
};

const sharedKeywordIntentRules: KeywordIntentRule[] = [
  {
    intent: "medicine",
    keywords: ["thuoc", "uong thuoc"],
    english: "I need to take medicine.",
    sample: "Thuoc",
  },
  {
    intent: "spilled_water",
    keywords: ["roi nuoc", "do nuoc", "lam roi nuoc"],
    english: "I spilled water.",
    sample: "Roi nuoc",
  },
  {
    intent: "water",
    keywords: ["nuoc", "khat"],
    english: "Can I have some water, please?",
    sample: "Con, nuoc",
    blockedKeywords: ["thuoc", "cong vien nuoc"],
  },
  {
    intent: "milk",
    keywords: ["sua"],
    english: "Can I have some milk, please?",
    sample: "Sua",
  },
  {
    intent: "eat",
    keywords: ["muon an", "an com", "an banh"],
    english: "I want to eat.",
    sample: "Muon an",
    blockedKeywords: ["an kem", "kem"],
  },
  {
    intent: "hungry",
    keywords: ["doi bung", "con doi", "dang doi"],
    english: "I'm hungry.",
    sample: "Doi",
  },
  {
    intent: "bathroom",
    keywords: ["ve sinh"],
    english: "I need to go to the bathroom.",
    sample: "Ve sinh",
  },
  {
    intent: "stomach_ache",
    keywords: ["dau bung"],
    english: "My stomach hurts.",
    sample: "Dau bung",
  },
  {
    intent: "head_ache",
    keywords: ["dau dau"],
    english: "My head hurts.",
    sample: "Dau dau",
  },
  {
    intent: "sick",
    keywords: ["bi om", "con om", "bi benh", "benh"],
    english: "I'm sick.",
    sample: "Bi om",
  },
  {
    intent: "hurt",
    keywords: ["dau"],
    english: "I got hurt.",
    sample: "Dau",
    blockedKeywords: ["dau bung", "dau dau", "me dau", "bo dau", "di dau", "o dau"],
  },
  {
    intent: "help",
    keywords: ["giup"],
    english: "Can you help me, please?",
    sample: "Giup con",
    blockedKeywords: ["co oi", "thay oi"],
  },
  {
    intent: "window_near",
    keywords: ["gan cua so"],
    english: "I want to stand near the window.",
    sample: "Cua so",
  },
  {
    intent: "airplane_sky",
    keywords: ["may bay tren troi", "may bay"],
    english: "I want to see the airplane in the sky.",
    sample: "May bay",
    blockedKeywords: ["nhin thay", "con thay"],
  },
  {
    intent: "elevator",
    keywords: ["di thang may", "thang may"],
    english: "Can we take the elevator?",
    sample: "Thang may",
  },
  {
    intent: "photo_with_statue",
    keywords: ["chup cho con voi buc tuong", "chup voi buc tuong"],
    english: "Mom, please take a picture of me with that statue.",
    sample: "Chup voi buc tuong",
  },
  {
    intent: "see_statue",
    keywords: ["nhin buc tuong", "xem buc tuong"],
    english: "I want to see that statue.",
    sample: "Nhin buc tuong",
  },
  {
    intent: "photo_with_me",
    keywords: ["chup cho con", "chup hinh cho con", "chup voi con"],
    english: "Please take a picture of me.",
    sample: "Chup cho con",
  },
  {
    intent: "tired",
    keywords: ["met"],
    english: "I'm tired.",
    sample: "Met",
  },
  {
    intent: "hot",
    keywords: ["nong"],
    english: "I'm hot.",
    sample: "Nong",
  },
  {
    intent: "cold",
    keywords: ["lanh"],
    english: "I'm cold.",
    sample: "Lanh",
  },
  {
    intent: "scared",
    keywords: ["con so", "so qua", "so lam", "con thay so"],
    english: "I'm scared.",
    sample: "Con so",
    blockedKeywords: ["cua so"],
  },
];

export const keywordIntentRules: Record<PracticeContext, KeywordIntentRule[]> = {
  home: [
    ...sharedKeywordIntentRules,
    {
      intent: "sleepy",
      keywords: ["buon ngu", "di ngu"],
      english: "I'm sleepy.",
      sample: "Buon ngu",
    },
    {
      intent: "bath",
      keywords: ["di tam", "tam"],
      english: "I want to take a bath.",
      sample: "Di tam",
    },
    {
      intent: "wash_hands",
      keywords: ["rua tay"],
      english: "I want to wash my hands.",
      sample: "Rua tay",
    },
    {
      intent: "story",
      keywords: ["doc truyen", "ke truyen"],
      english: "Mom, please read me a story.",
      sample: "Doc truyen",
    },
    {
      intent: "cartoon",
      keywords: ["phim hoat hinh", "xem phim"],
      english: "I want to watch cartoons.",
      sample: "Xem phim hoat hinh",
    },
    {
      intent: "play_with_parent",
      keywords: ["bo choi", "me choi", "choi voi con"],
      english: "Please play with me.",
      sample: "Choi voi con",
    },
    {
      intent: "play",
      keywords: ["choi"],
      english: "I want to play.",
      sample: "Choi",
    },
    {
      intent: "hug",
      keywords: ["om con", "can om"],
      english: "I need a hug.",
      sample: "Om con",
      blockedKeywords: ["bi om"],
    },
    {
      intent: "this_and_that",
      keywords: ["cai nay cai kia", "nay kia"],
      english: "I want this one and that one.",
      sample: "Cai nay cai kia",
    },
    {
      intent: "this_one",
      keywords: ["cai nay"],
      english: "I want this one.",
      sample: "Cai nay",
    },
    {
      intent: "that_one",
      keywords: ["cai kia"],
      english: "I want that one.",
      sample: "Cai kia",
    },
  ],
  school: [
    ...sharedKeywordIntentRules,
    {
      intent: "lost_pencil",
      keywords: ["mat but"],
      english: "I lost my pencil.",
      sample: "Mat but",
    },
    {
      intent: "pencil",
      keywords: ["but chi", "but"],
      english: "I need a pencil, please.",
      sample: "But chi",
      blockedKeywords: ["got but"],
    },
    {
      intent: "book",
      keywords: ["quen sach"],
      english: "I forgot my book.",
      sample: "Sach",
    },
    {
      intent: "notebook",
      keywords: ["quen vo"],
      english: "I forgot my notebook.",
      sample: "Vo",
    },
    {
      intent: "dont_understand",
      keywords: ["khong hieu"],
      english: "I don't understand.",
      sample: "Khong hieu",
    },
    {
      intent: "more_time",
      keywords: ["them thoi gian"],
      english: "I need more time.",
      sample: "Them thoi gian",
    },
    {
      intent: "teacher_help",
      keywords: ["co oi", "thay oi"],
      english: "Teacher, I need help, please.",
      sample: "Co oi",
    },
    {
      intent: "ask_teacher",
      keywords: ["hoi co", "hoi thay"],
      english: "I want to ask the teacher.",
      sample: "Hoi co",
    },
    {
      intent: "finished",
      keywords: ["xong roi"],
      english: "I'm finished.",
      sample: "Xong roi",
    },
    {
      intent: "unfinished",
      keywords: ["chua xong", "chua lam xong"],
      english: "I'm not finished yet.",
      sample: "Chua xong",
    },
    {
      intent: "friend_took_item",
      keywords: ["ban lay", "lay do"],
      english: "My friend took my thing.",
      sample: "Ban lay do",
    },
    {
      intent: "friend_pushed",
      keywords: ["ban day", "bi day"],
      english: "My friend pushed me.",
      sample: "Ban day con",
    },
    {
      intent: "change_seat",
      keywords: ["doi cho", "cho ngoi"],
      english: "Can I change seats, please?",
      sample: "Doi cho",
    },
    {
      intent: "play_with_friend",
      keywords: ["choi voi ban"],
      english: "I want to play with my friend.",
      sample: "Choi voi ban",
    },
  ],
  outside: [
    ...sharedKeywordIntentRules,
    {
      intent: "water_park",
      keywords: ["cong vien nuoc"],
      english: "Can we go to the water park?",
      sample: "Cong vien nuoc",
    },
    {
      intent: "where_go",
      keywords: ["di dau", "di choi gi", "di choi dau"],
      english: "Where are we going today?",
      sample: "Di dau",
    },
    {
      intent: "go_home",
      keywords: ["ve nha"],
      english: "I want to go home.",
      sample: "Ve nha",
    },
    {
      intent: "lost",
      keywords: ["lac"],
      english: "I'm lost. I need help.",
      sample: "Bi lac",
    },
    {
      intent: "buy",
      keywords: ["mua"],
      english: "Can we buy this?",
      sample: "Mua cai nay",
    },
    {
      intent: "see_this",
      keywords: ["xem cai nay", "xem cai kia"],
      english: "I want to see this.",
      sample: "Xem cai nay",
    },
    {
      intent: "see_robot",
      keywords: ["xem con robot", "xem robot"],
      english: "I want to see the robot.",
      sample: "Xem robot",
    },
    {
      intent: "take_photo",
      keywords: ["chup anh", "chup hinh"],
      english: "I want to take a picture.",
      sample: "Chup anh",
    },
    {
      intent: "this_and_that",
      keywords: ["cai nay cai kia", "nay kia"],
      english: "I want this one and that one.",
      sample: "Cai nay cai kia",
    },
    {
      intent: "this_one",
      keywords: ["cai nay"],
      english: "I want this one.",
      sample: "Cai nay",
    },
    {
      intent: "that_one",
      keywords: ["cai kia"],
      english: "I want that one.",
      sample: "Cai kia",
    },
    {
      intent: "ice_cream",
      keywords: ["kem", "an kem"],
      english: "I want some ice cream.",
      sample: "An kem",
    },
    {
      intent: "park",
      keywords: ["cong vien"],
      english: "Can we go to the park?",
      sample: "Cong vien",
    },
    {
      intent: "crowd",
      keywords: ["dong nguoi", "nhieu nguoi"],
      english: "There are too many people. I'm scared.",
      sample: "Dong nguoi",
    },
    {
      intent: "cannot_find_mom",
      keywords: ["khong thay me", "me dau", "lac me"],
      english: "I can't see Mom.",
      sample: "Me dau",
    },
  ],
};

export function getRuleAudioTexts(context: PracticeContext) {
  const texts = [
    ...phraseRules[context].map((rule) => rule.english),
    ...keywordIntentRules[context].map((rule) => rule.english),
  ];

  return [...new Set(texts)];
}
