export const regionalVocabularyRowsV1 = [
  {"sourceRow":2,"standard":"ảnh","south":"hình","central":"hình","north":"ảnh"},
  {"sourceRow":3,"standard":"anh","south":"anh","central":"eng","north":"anh"},
  {"sourceRow":8,"standard":"ăn gì","south":"ăn gì","central":"ăn chi","north":"ăn gì"},
  {"sourceRow":10,"standard":"bà","south":"bà","central":"mệ","north":"bà"},
  {"sourceRow":18,"standard":"bánh","south":"bánh","central":"béng","north":"bánh"},
  {"sourceRow":22,"standard":"bảo","south":"biểu","central":"bảo","north":"bẩu"},
  {"sourceRow":25,"standard":"bát","south":"chén","central":"đọi","north":"bát"},
  {"sourceRow":27,"standard":"bẩn","south":"dơ","central":"dơ","north":"bẩn"},
  {"sourceRow":30,"standard":"bây giờ","south":"bây giờ","central":"chừ","north":"bây giờ"},
  {"sourceRow":36,"standard":"bên kia","south":"bên bển","central":"bên tê","north":"bên kia"},
  {"sourceRow":37,"standard":"bên này","south":"bên này","central":"bên ni","north":"bên này"},
  {"sourceRow":43,"standard":"bố","south":"ba","central":"bọ","north":"bố"},
  {"sourceRow":44,"standard":"bố mẹ","south":"ba má","central":"bọ mạ","north":"thầy u"},
  {"sourceRow":49,"standard":"bơi","south":"lội","central":"bơi","north":"bơi"},
  {"sourceRow":54,"standard":"buộc","south":"cột","central":"buộc","north":"buộc"},
  {"sourceRow":55,"standard":"buộc dây","south":"buộc dây","central":"buộc chạc","north":"buộc dây"},
  {"sourceRow":57,"standard":"buổi tối","south":"buổi tối","central":"buổi túi","north":"buổi tối"},
  {"sourceRow":62,"standard":"bút","south":"cây viết","central":"bút","north":"bút"},
  {"sourceRow":64,"standard":"bút chì","south":"cây viết chì","central":"bút chì","north":"bút chì"},
  {"sourceRow":65,"standard":"bữa","south":"bữa","central":"bựa","north":"bữa"},
  {"sourceRow":66,"standard":"bức ảnh","south":"tấm hình","central":"bức ảnh","north":"bức ảnh"},
  {"sourceRow":69,"standard":"cái","south":"cái","central":"cấy","north":"cái"},
  {"sourceRow":74,"standard":"cái này","south":"cái này","central":"cấy ni","north":"cái này"},
  {"sourceRow":81,"standard":"cây","south":"cây","central":"cơn","north":"cây"},
  {"sourceRow":87,"standard":"chăn","south":"mền","central":"mền","north":"chăn"},
  {"sourceRow":91,"standard":"chân","south":"chưn","central":"chân","north":"chân"},
  {"sourceRow":96,"standard":"chiều nay","south":"chiều nay","central":"chiều ni","north":"chiều nay"},
  {"sourceRow":99,"standard":"chơi","south":"chơi","central":"nhởi","north":"chơi"},
  {"sourceRow":102,"standard":"chụp ảnh","south":"chụp hình","central":"chụp ảnh","north":"chụp ảnh"},
  {"sourceRow":104,"standard":"chưa","south":"chưa","central":"chửa","north":"chửa"},
  {"sourceRow":107,"standard":"còn","south":"còn","central":"lưa","north":"còn"},
  {"sourceRow":110,"standard":"còn lại","south":"còn lại","central":"còn lưa","north":"còn lại"},
  {"sourceRow":112,"standard":"cô","south":"cô","central":"o","north":"cô"},
  {"sourceRow":114,"standard":"cố gắng","south":"ráng","central":"cố gắng","north":"cố gắng"},
  {"sourceRow":116,"standard":"cốc","south":"ly","central":"ly","north":"cốc"},
  {"sourceRow":124,"standard":"cửa hàng","south":"tiệm","central":"cửa hàng","north":"cửa hàng"},
  {"sourceRow":131,"standard":"dây","south":"dây","central":"chạc","north":"dây"},
  {"sourceRow":136,"standard":"dễ","south":"dễ","central":"dệ","north":"dễ"},
  {"sourceRow":144,"standard":"đá bóng","south":"đá banh","central":"đá bóng","north":"đá bóng"},
  {"sourceRow":145,"standard":"đàn","south":"đờn","central":"đàn","north":"đàn"},
  {"sourceRow":153,"standard":"đắt","south":"mắc","central":"mắc","north":"đắt"},
  {"sourceRow":155,"standard":"đắt quá","south":"mắc quá","central":"đắt quá","north":"đắt quá"},
  {"sourceRow":156,"standard":"đâu","south":"đâu","central":"mô","north":"đâu"},
  {"sourceRow":157,"standard":"đầu","south":"đầu","central":"trốc","north":"đầu"},
  {"sourceRow":161,"standard":"để","south":"đặng","central":"để","north":"để"},
  {"sourceRow":162,"standard":"đến","south":"tới","central":"đến","north":"đến"},
  {"sourceRow":163,"standard":"đến muộn","south":"đến trễ","central":"đến trễ","north":"đến muộn"},
  {"sourceRow":164,"standard":"đi chơi","south":"đi chơi","central":"đi nhởi","north":"đi chơi"},
  {"sourceRow":165,"standard":"đi đâu","south":"đi đâu","central":"đi mô","north":"đi đâu"},
  {"sourceRow":168,"standard":"đi vào","south":"đi vô","central":"đi vô","north":"đi vào"},
  {"sourceRow":169,"standard":"đi vệ sinh","south":"đi cầu","central":"đi vệ sinh","north":"đi vệ sinh"},
  {"sourceRow":173,"standard":"đó","south":"đó","central":"nớ","north":"đó"},
  {"sourceRow":175,"standard":"đón","south":"rước","central":"rước","north":"đón"},
  {"sourceRow":187,"standard":"đuổi","south":"rượt","central":"đuổi","north":"đuổi"},
  {"sourceRow":190,"standard":"đừng","south":"đừng","central":"đừng","north":"chớ"},
  {"sourceRow":191,"standard":"đường","south":"đường","central":"đàng","north":"đường"},
  {"sourceRow":192,"standard":"đường đi","south":"đường đi","central":"đàng đi","north":"đường đi"},
  {"sourceRow":197,"standard":"gần","south":"gần","central":"gưn","north":"gần"},
  {"sourceRow":201,"standard":"gì","south":"gì","central":"chi","north":"gì"},
  {"sourceRow":214,"standard":"giúp","south":"giùm","central":"giúp","north":"giúp"},
  {"sourceRow":216,"standard":"gọi","south":"kêu","central":"kêu","north":"gọi"},
  {"sourceRow":217,"standard":"gọi tên","south":"kêu tên","central":"gọi tên","north":"gọi tên"},
  {"sourceRow":218,"standard":"gửi","south":"gởi","central":"gửi","north":"gửi"},
  {"sourceRow":228,"standard":"hoa","south":"bông","central":"bông","north":"hoa"},
  {"sourceRow":236,"standard":"hôm nay","south":"hôm nay","central":"bữa ni","north":"hôm nay"},
  {"sourceRow":238,"standard":"hôm sau","south":"bữa sau","central":"hôm sau","north":"hôm sau"},
  {"sourceRow":246,"standard":"khỏe","south":"phẻ","central":"khỏe","north":"khỏe"},
  {"sourceRow":247,"standard":"không","south":"hông","central":"nỏ","north":"không"},
  {"sourceRow":248,"standard":"không biết","south":"không biết","central":"không biết","north":"chả biết"},
  {"sourceRow":254,"standard":"không thích","south":"không thích","central":"nỏ ưng","north":"không thích"},
  {"sourceRow":255,"standard":"không tìm thấy","south":"kiếm hổng ra","central":"không tìm thấy","north":"không tìm thấy"},
  {"sourceRow":257,"standard":"kia","south":"kia","central":"tê","north":"kia"},
  {"sourceRow":258,"standard":"kìa","south":"kìa","central":"tề","north":"kìa"},
  {"sourceRow":266,"standard":"làm","south":"làm","central":"mần","north":"làm"},
  {"sourceRow":268,"standard":"làm gì","south":"làm gì","central":"làm chi","north":"làm gì"},
  {"sourceRow":270,"standard":"lau","south":"lau","central":"chùi","north":"lau"},
  {"sourceRow":271,"standard":"lấy","south":"lấy","central":"bợ","north":"lấy"},
  {"sourceRow":277,"standard":"lời","south":"lời","central":"lời","north":"nhời"},
  {"sourceRow":288,"standard":"mang","south":"rinh","central":"mang","north":"mang"},
  {"sourceRow":293,"standard":"màu","south":"màu","central":"màu","north":"mầu"},
  {"sourceRow":306,"standard":"mẹ","south":"má","central":"mạ","north":"u"},
  {"sourceRow":308,"standard":"mình","south":"mình","central":"miềng","north":"mình"},
  {"sourceRow":309,"standard":"mọi người","south":"bà con","central":"mọi người","north":"mọi người"},
  {"sourceRow":312,"standard":"một chút","south":"một xíu","central":"một chút","north":"một chút"},
  {"sourceRow":313,"standard":"một lát","south":"một hồi","central":"một lát","north":"một lát"},
  {"sourceRow":315,"standard":"mũ","south":"nón","central":"nón","north":"mũ"},
  {"sourceRow":323,"standard":"muộn","south":"trễ","central":"trễ","north":"muộn"},
  {"sourceRow":329,"standard":"này","south":"nè","central":"ni","north":"này"},
  {"sourceRow":335,"standard":"ngã","south":"té","central":"bổ","north":"ngã"},
  {"sourceRow":339,"standard":"ngay","south":"liền","central":"ngay","north":"ngay"},
  {"sourceRow":355,"standard":"nhà vệ sinh","south":"nhà cầu","central":"nhà vệ sinh","north":"nhà vệ sinh"},
  {"sourceRow":361,"standard":"nhặt","south":"lượm","central":"lặt","north":"nhặt"},
  {"sourceRow":363,"standard":"nhầm","south":"lộn","central":"nhầm","north":"nhầm"},
  {"sourceRow":366,"standard":"nhất","south":"nhứt","central":"nhất","north":"nhất"},
  {"sourceRow":367,"standard":"nhé","south":"nha","central":"nhé","north":"nhá"},
  {"sourceRow":368,"standard":"nhỉ","south":"nhỉ","central":"hè","north":"nhở"},
  {"sourceRow":369,"standard":"nhìn","south":"nhìn","central":"ngó","north":"nom"},
  {"sourceRow":370,"standard":"nhìn thấy","south":"nhìn thấy","central":"chộ","north":"nhìn thấy"},
  {"sourceRow":382,"standard":"nữa","south":"nữa","central":"nựa","north":"nữa"},
  {"sourceRow":383,"standard":"nước","south":"nước","central":"nác","north":"nước"},
  {"sourceRow":391,"standard":"ô","south":"dù","central":"dù","north":"ô"},
  {"sourceRow":396,"standard":"ở đâu","south":"ở đâu","central":"ở mô","north":"ở đâu"},
  {"sourceRow":397,"standard":"ở đây","south":"ở đây","central":"ở ni","north":"ở đây"},
  {"sourceRow":400,"standard":"ở trên","south":"ở trển","central":"ở trên","north":"ở trên"},
  {"sourceRow":411,"standard":"quả","south":"trái","central":"trái","north":"quả"},
  {"sourceRow":412,"standard":"quả bóng","south":"trái banh","central":"trái banh","north":"quả bóng"},
  {"sourceRow":415,"standard":"quả cam","south":"trái cam","central":"quả cam","north":"quả cam"},
  {"sourceRow":417,"standard":"quả chuối","south":"trái chuối","central":"quả chuối","north":"quả chuối"},
  {"sourceRow":426,"standard":"quả táo","south":"trái táo","central":"quả táo","north":"quả táo"},
  {"sourceRow":439,"standard":"rẽ","south":"quẹo","central":"quẹo","north":"rẽ"},
  {"sourceRow":444,"standard":"rồi","south":"rầu","central":"rồi","north":"rồi"},
  {"sourceRow":450,"standard":"sai","south":"trật","central":"sai","north":"sai"},
  {"sourceRow":452,"standard":"sao","south":"sao","central":"răng","north":"sao"},
  {"sourceRow":454,"standard":"sau này","south":"mai mốt","central":"sau này","north":"sau này"},
  {"sourceRow":458,"standard":"sân","south":"sân","central":"cươi","north":"sân"},
  {"sourceRow":465,"standard":"sợ","south":"ớn","central":"hại","north":"sợ"},
  {"sourceRow":474,"standard":"táo","south":"bôm","central":"táo","north":"táo"},
  {"sourceRow":476,"standard":"tàu","south":"tàu","central":"tàu","north":"tầu"},
  {"sourceRow":480,"standard":"tầng","south":"lầu","central":"tầng","north":"tầng"},
  {"sourceRow":482,"standard":"tất","south":"vớ","central":"vớ","north":"tất"},
  {"sourceRow":485,"standard":"thanh toán","south":"tính tiền","central":"trả tiền","north":"thanh toán"},
  {"sourceRow":491,"standard":"thấy","south":"thấy","central":"chộ","north":"thấy"},
  {"sourceRow":493,"standard":"thế nào","south":"thế nào","central":"răng rứa","north":"thế nào"},
  {"sourceRow":498,"standard":"thích","south":"khoái","central":"ưng","north":"thích"},
  {"sourceRow":503,"standard":"thôi","south":"thâu","central":"thôi","north":"thôi"},
  {"sourceRow":508,"standard":"thử xem","south":"thử coi","central":"thử xem","north":"thử xem"},
  {"sourceRow":514,"standard":"tìm","south":"kiếm","central":"tìm","north":"tìm"},
  {"sourceRow":517,"standard":"to","south":"bự","central":"to","north":"to"},
  {"sourceRow":519,"standard":"tối nay","south":"tối nay","central":"túi ni","north":"tối nay"},
  {"sourceRow":524,"standard":"trái","south":"trái","central":"trấy","north":"trái"},
  {"sourceRow":526,"standard":"tránh","south":"né","central":"tránh","north":"tránh"},
  {"sourceRow":532,"standard":"trên đường","south":"trên đường","central":"trên đàng","north":"trên đường"},
  {"sourceRow":539,"standard":"trông em","south":"coi em","central":"trông em","north":"trông em"},
  {"sourceRow":540,"standard":"trời","south":"trời","central":"trời","north":"giời"},
  {"sourceRow":549,"standard":"vào","south":"vô","central":"vô","north":"vào"},
  {"sourceRow":553,"standard":"vậy","south":"vậy","central":"rứa","north":"thế"},
  {"sourceRow":555,"standard":"về","south":"dìa","central":"về","north":"về"},
  {"sourceRow":557,"standard":"ví dụ","south":"thí dụ","central":"ví dụ","north":"ví dụ"},
  {"sourceRow":562,"standard":"vui","south":"vui","central":"bui","north":"vui"},
  {"sourceRow":570,"standard":"xe máy","south":"xe gắn máy","central":"xe máy","north":"xe máy"},
  {"sourceRow":571,"standard":"xem","south":"coi","central":"coi","north":"xem"},
  {"sourceRow":573,"standard":"xem phim","south":"coi phim","central":"xem phim","north":"xem phim"},
] as const;

