/**
 * Generated from tu-vung-toan-dan-co-bien-the-3-mien-mo-rong.xlsx.
 * Source rows are retained so normalization telemetry can be audited against
 * the reviewed workbook without exposing the workbook to the runtime.
 */
export const allRegionalVocabularyRowsV1 = [
  {"sourceRow":2,"standard":"ảnh","south":"hình","central":"hình","north":"ảnh"},
  {"sourceRow":3,"standard":"anh","south":"anh","central":"eng","north":"anh"},
  {"sourceRow":4,"standard":"anh ấy","south":"ảnh","central":"anh ấy","north":"anh ấy"},
  {"sourceRow":5,"standard":"anh cả","south":"anh hai","central":"anh cả","north":"anh cả"},
  {"sourceRow":6,"standard":"áo phông","south":"áo thun","central":"áo thun","north":"áo phông"},
  {"sourceRow":7,"standard":"áo rét","south":"áo lạnh","central":"áo rét","north":"áo rét"},
  {"sourceRow":8,"standard":"ăn gì","south":"ăn gì","central":"ăn chi","north":"ăn gì"},
  {"sourceRow":9,"standard":"ăn thua gì","south":"nhằm nhò gì","central":"ăn thua gì","north":"ăn thua gì"},
  {"sourceRow":10,"standard":"bà","south":"bà","central":"mệ","north":"bà"},
  {"sourceRow":11,"standard":"bà ấy","south":"bả","central":"bà ấy","north":"bà ấy"},
  {"sourceRow":12,"standard":"bà mối","south":"bà mai","central":"bà mối","north":"bà mối"},
  {"sourceRow":13,"standard":"bạc màu","south":"lợt màu","central":"bạc màu","north":"bạc màu"},
  {"sourceRow":14,"standard":"bán buôn","south":"bán sỉ","central":"bán buôn","north":"bán buôn"},
  {"sourceRow":15,"standard":"bán hết","south":"bán sạch trơn","central":"bán hết","north":"bán hết"},
  {"sourceRow":16,"standard":"bàn là","south":"bàn ủi","central":"bàn là","north":"bàn là"},
  {"sourceRow":17,"standard":"bán rong","south":"bán dạo","central":"bán rong","north":"bán rong"},
  {"sourceRow":18,"standard":"bánh","south":"bánh","central":"béng","north":"bánh"},
  {"sourceRow":19,"standard":"bánh cuốn","south":"bánh ướt","central":"bánh cuốn","north":"bánh cuốn"},
  {"sourceRow":20,"standard":"bánh đa nem","south":"bánh tráng cuốn","central":"bánh đa nem","north":"bánh đa nem"},
  {"sourceRow":21,"standard":"bánh tráng","south":"bánh tráng","central":"bánh tráng","north":"bánh đa"},
  {"sourceRow":22,"standard":"bảo","south":"biểu","central":"bảo","north":"bẩu"},
  {"sourceRow":23,"standard":"bao giờ","south":"bao giờ","central":"răng chừ","north":"bao giờ"},
  {"sourceRow":24,"standard":"bao tải","south":"bao bố","central":"bao tải","north":"bao tải"},
  {"sourceRow":25,"standard":"bát","south":"chén","central":"đọi","north":"bát"},
  {"sourceRow":26,"standard":"bắt đền","south":"bắt thường","central":"bắt đền","north":"bắt đền"},
  {"sourceRow":27,"standard":"bẩn","south":"dơ","central":"dơ","north":"bẩn"},
  {"sourceRow":28,"standard":"bận việc","south":"mắc việc","central":"bận việc","north":"bận việc"},
  {"sourceRow":29,"standard":"bật quạt","south":"mở quạt","central":"bật quạt","north":"bật quạt"},
  {"sourceRow":30,"standard":"bây giờ","south":"bây giờ","central":"chừ","north":"bây giờ"},
  {"sourceRow":31,"standard":"bé","south":"nhỏ","central":"bé","north":"bé"},
  {"sourceRow":32,"standard":"bé tí","south":"nhỏ xíu","central":"bé tí","north":"bé tí"},
  {"sourceRow":33,"standard":"béo","south":"mập","central":"mập","north":"béo"},
  {"sourceRow":34,"standard":"bế","south":"ẵm","central":"bồng","north":"bế"},
  {"sourceRow":35,"standard":"bên ấy","south":"bển","central":"bên ấy","north":"bên ấy"},
  {"sourceRow":36,"standard":"bên kia","south":"bên bển","central":"bên tê","north":"bên kia"},
  {"sourceRow":37,"standard":"bên này","south":"bên này","central":"bên ni","north":"bên này"},
  {"sourceRow":38,"standard":"bệnh","south":"bịnh","central":"bệnh","north":"bệnh"},
  {"sourceRow":39,"standard":"bệnh viện","south":"nhà thương","central":"bệnh viện","north":"bệnh viện"},
  {"sourceRow":40,"standard":"bí đỏ","south":"bí rợ","central":"bí đỏ","north":"bí đỏ"},
  {"sourceRow":41,"standard":"bí ngô","south":"bí rợ","central":"bí ngô","north":"bí ngô"},
  {"sourceRow":42,"standard":"bỏ vào","south":"bỏ vô","central":"bỏ vào","north":"bỏ vào"},
  {"sourceRow":43,"standard":"bố","south":"ba","central":"bọ","north":"bố"},
  {"sourceRow":44,"standard":"bố mẹ","south":"ba má","central":"bọ mạ","north":"thầy u"},
  {"sourceRow":45,"standard":"bốc phét","south":"nói dóc","central":"bốc phét","north":"bốc phét"},
  {"sourceRow":46,"standard":"bốc thăm","south":"bắt thăm","central":"bốc thăm","north":"bốc thăm"},
  {"sourceRow":47,"standard":"bồn cầu","south":"bàn cầu","central":"bồn cầu","north":"bồn cầu"},
  {"sourceRow":48,"standard":"bột ngọt","south":"bột ngọt","central":"bột ngọt","north":"mì chính"},
  {"sourceRow":49,"standard":"bơi","south":"lội","central":"bơi","north":"bơi"},
  {"sourceRow":50,"standard":"bới","south":"bươi","central":"bới","north":"bới"},
  {"sourceRow":51,"standard":"bớt","south":"bớt","central":"bớt","north":"vợi"},
  {"sourceRow":52,"standard":"bụi tre","south":"lùm tre","central":"bụi tre","north":"bụi tre"},
  {"sourceRow":53,"standard":"bùn","south":"sình","central":"bùn","north":"bùn"},
  {"sourceRow":54,"standard":"buộc","south":"cột","central":"buộc","north":"buộc"},
  {"sourceRow":55,"standard":"buộc dây","south":"buộc dây","central":"buộc chạc","north":"buộc dây"},
  {"sourceRow":56,"standard":"buộc lại","south":"cột lại","central":"buộc lại","north":"buộc lại"},
  {"sourceRow":57,"standard":"buổi tối","south":"buổi tối","central":"buổi túi","north":"buổi tối"},
  {"sourceRow":58,"standard":"buổi trưa","south":"buổi trưa","central":"buổi trửa","north":"buổi trưa"},
  {"sourceRow":59,"standard":"buồn cười","south":"mắc cười","central":"buồn cười","north":"buồn cười"},
  {"sourceRow":60,"standard":"buồn nôn","south":"mắc ói","central":"buồn nôn","north":"buồn nôn"},
  {"sourceRow":61,"standard":"buồn tiểu","south":"mắc tiểu","central":"buồn tiểu","north":"buồn tiểu"},
  {"sourceRow":62,"standard":"bút","south":"cây viết","central":"bút","north":"bút"},
  {"sourceRow":63,"standard":"bút bi","south":"cây viết bi","central":"bút bi","north":"bút bi"},
  {"sourceRow":64,"standard":"bút chì","south":"cây viết chì","central":"bút chì","north":"bút chì"},
  {"sourceRow":65,"standard":"bữa","south":"bữa","central":"bựa","north":"bữa"},
  {"sourceRow":66,"standard":"bức ảnh","south":"tấm hình","central":"bức ảnh","north":"bức ảnh"},
  {"sourceRow":67,"standard":"cá quả","south":"cá lóc","central":"cá tràu","north":"cá quả"},
  {"sourceRow":68,"standard":"cá voi","south":"cá ông","central":"cá voi","north":"cá voi"},
  {"sourceRow":69,"standard":"cái","south":"cái","central":"cấy","north":"cái"},
  {"sourceRow":70,"standard":"cải cúc","south":"tần ô","central":"tần ô","north":"cải cúc"},
  {"sourceRow":71,"standard":"cái đĩa","south":"cái dĩa","central":"cái đĩa","north":"cái đĩa"},
  {"sourceRow":72,"standard":"cái gì","south":"cái gì","central":"cái chi","north":"cái gì"},
  {"sourceRow":73,"standard":"cái kia","south":"cái kia","central":"cấy tê","north":"cái kia"},
  {"sourceRow":74,"standard":"cái này","south":"cái này","central":"cấy ni","north":"cái này"},
  {"sourceRow":75,"standard":"cãi nhau","south":"cãi lộn","central":"cãi nhau","north":"cãi nhau"},
  {"sourceRow":76,"standard":"canh mướp đắng","south":"canh khổ qua","central":"canh mướp đắng","north":"canh mướp đắng"},
  {"sourceRow":77,"standard":"cáu","south":"quạu","central":"cáu","north":"cáu"},
  {"sourceRow":78,"standard":"cắt tóc","south":"hớt tóc","central":"cắt tóc","north":"cắt tóc"},
  {"sourceRow":79,"standard":"cầm hộ","south":"cầm giùm","central":"cầm hộ","north":"cầm hộ"},
  {"sourceRow":80,"standard":"cất đi","south":"dẹp đi","central":"cất đi","north":"cất đi"},
  {"sourceRow":81,"standard":"cây","south":"cây","central":"cơn","north":"cây"},
  {"sourceRow":82,"standard":"cha","south":"ba","central":"ba","north":"bố"},
  {"sourceRow":83,"standard":"chạm vào","south":"đụng vô","central":"chạm vào","north":"chạm vào"},
  {"sourceRow":84,"standard":"chanh leo","south":"chanh dây","central":"chanh dây","north":"chanh leo"},
  {"sourceRow":85,"standard":"chảo rán","south":"chảo chiên","central":"chảo rán","north":"chảo rán"},
  {"sourceRow":86,"standard":"chăm chỉ","south":"siêng năng","central":"chăm chỉ","north":"chăm chỉ"},
  {"sourceRow":87,"standard":"chăn","south":"mền","central":"mền","north":"chăn"},
  {"sourceRow":88,"standard":"chăn màn","south":"mền mùng","central":"chăn màn","north":"chăn màn"},
  {"sourceRow":89,"standard":"chăn trâu","south":"chăn trâu","central":"chăn tru","north":"chăn trâu"},
  {"sourceRow":90,"standard":"chẳng","south":"chẳng","central":"chẳng","north":"chả"},
  {"sourceRow":91,"standard":"chân","south":"chưn","central":"chân","north":"chân"},
  {"sourceRow":92,"standard":"chết đuối","south":"chết trôi","central":"chết đuối","north":"chết đuối"},
  {"sourceRow":93,"standard":"chị","south":"chị","central":"ả","north":"chị"},
  {"sourceRow":94,"standard":"chị ấy","south":"chỉ","central":"chị ấy","north":"chị ấy"},
  {"sourceRow":95,"standard":"chị cả","south":"chị hai","central":"chị cả","north":"chị cả"},
  {"sourceRow":96,"standard":"chiều nay","south":"chiều nay","central":"chiều ni","north":"chiều nay"},
  {"sourceRow":97,"standard":"chồng","south":"chồng","central":"nhông","north":"chồng"},
  {"sourceRow":98,"standard":"chở","south":"chở","central":"chở","north":"lai"},
  {"sourceRow":99,"standard":"chơi","south":"chơi","central":"nhởi","north":"chơi"},
  {"sourceRow":100,"standard":"chơi đùa","south":"chơi giỡn","central":"chơi đùa","north":"chơi đùa"},
  {"sourceRow":101,"standard":"chum","south":"lu","central":"chum","north":"chum"},
  {"sourceRow":102,"standard":"chụp ảnh","south":"chụp hình","central":"chụp ảnh","north":"chụp ảnh"},
  {"sourceRow":103,"standard":"chứ","south":"chớ","central":"chơ","north":"chứ"},
  {"sourceRow":104,"standard":"chưa","south":"chưa","central":"chửa","north":"chửa"},
  {"sourceRow":105,"standard":"chưa xong","south":"chưa xong","central":"chưa xong","north":"chửa xong"},
  {"sourceRow":106,"standard":"coi thi","south":"gác thi","central":"coi thi","north":"coi thi"},
  {"sourceRow":107,"standard":"còn","south":"còn","central":"lưa","north":"còn"},
  {"sourceRow":108,"standard":"con dâu","south":"con dâu","central":"con du","north":"con dâu"},
  {"sourceRow":109,"standard":"con gái","south":"con gái","central":"con gấy","north":"con gái"},
  {"sourceRow":110,"standard":"còn lại","south":"còn lại","central":"còn lưa","north":"còn lại"},
  {"sourceRow":111,"standard":"con trâu","south":"con trâu","central":"con tru","north":"con trâu"},
  {"sourceRow":112,"standard":"cô","south":"cô","central":"o","north":"cô"},
  {"sourceRow":113,"standard":"cô ấy","south":"cổ","central":"cô ấy","north":"cô ấy"},
  {"sourceRow":114,"standard":"cố gắng","south":"ráng","central":"cố gắng","north":"cố gắng"},
  {"sourceRow":115,"standard":"cổ vũ","south":"cổ võ","central":"cổ vũ","north":"cổ vũ"},
  {"sourceRow":116,"standard":"cốc","south":"ly","central":"ly","north":"cốc"},
  {"sourceRow":117,"standard":"cơm rang","south":"cơm chiên","central":"cơm chiên","north":"cơm rang"},
  {"sourceRow":118,"standard":"cù","south":"chọc lét","central":"thọc lét","north":"cù"},
  {"sourceRow":119,"standard":"củ sắn","south":"củ khoai mì","central":"củ sắn","north":"củ sắn"},
  {"sourceRow":120,"standard":"cúc áo","south":"nút áo","central":"cúc áo","north":"cúc áo"},
  {"sourceRow":121,"standard":"cũng","south":"cũng","central":"cụng","north":"cũng"},
  {"sourceRow":122,"standard":"cúng bái","south":"cúng quải","central":"cúng bái","north":"cúng bái"},
  {"sourceRow":123,"standard":"cuống lên","south":"quýnh lên","central":"cuống lên","north":"cuống lên"},
  {"sourceRow":124,"standard":"cửa hàng","south":"tiệm","central":"cửa hàng","north":"cửa hàng"},
  {"sourceRow":125,"standard":"cực kỳ","south":"dễ sợ","central":"cực kỳ","north":"cực kỳ"},
  {"sourceRow":126,"standard":"dạ dày","south":"bao tử","central":"dạ dày","north":"dạ dày"},
  {"sourceRow":127,"standard":"dày","south":"dày","central":"dày","north":"dầy"},
  {"sourceRow":128,"standard":"dầu hỏa","south":"dầu hôi","central":"dầu hỏa","north":"dầu hỏa"},
  {"sourceRow":129,"standard":"dầu lạc","south":"dầu phộng","central":"dầu lạc","north":"dầu lạc"},
  {"sourceRow":130,"standard":"dầu nhờn","south":"nhớt","central":"dầu nhờn","north":"dầu nhờn"},
  {"sourceRow":131,"standard":"dây","south":"dây","central":"chạc","north":"dây"},
  {"sourceRow":132,"standard":"dây chun","south":"dây thun","central":"dây chun","north":"dây cao su"},
  {"sourceRow":133,"standard":"dây thép gai","south":"dây kẽm gai","central":"dây thép gai","north":"dây thép gai"},
  {"sourceRow":134,"standard":"dây thừng","south":"dây thừng","central":"chạc thừng","north":"dây thừng"},
  {"sourceRow":135,"standard":"dép lê","south":"dép lào","central":"dép lê","north":"dép lê"},
  {"sourceRow":136,"standard":"dễ","south":"dễ","central":"dệ","north":"dễ"},
  {"sourceRow":137,"standard":"diêm","south":"hộp quẹt","central":"diêm","north":"diêm"},
  {"sourceRow":138,"standard":"dính dáng","south":"mắc mớ","central":"dính dáng","north":"dính dáng"},
  {"sourceRow":139,"standard":"dọa","south":"hăm","central":"dọa","north":"dọa"},
  {"sourceRow":140,"standard":"dọc mùng","south":"bạc hà","central":"dọc mùng","north":"dọc mùng"},
  {"sourceRow":141,"standard":"dứa","south":"thơm","central":"thơm","north":"dứa"},
  {"sourceRow":142,"standard":"dưa chuột","south":"dưa leo","central":"dưa leo","north":"dưa chuột"},
  {"sourceRow":143,"standard":"dưới cây","south":"dưới cây","central":"dưới cơn","north":"dưới cây"},
  {"sourceRow":144,"standard":"đá bóng","south":"đá banh","central":"đá bóng","north":"đá bóng"},
  {"sourceRow":145,"standard":"đàn","south":"đờn","central":"đàn","north":"đàn"},
  {"sourceRow":146,"standard":"đàn nguyệt","south":"đờn kìm","central":"đàn nguyệt","north":"đàn nguyệt"},
  {"sourceRow":147,"standard":"đáng sợ","south":"dễ sợ","central":"đáng sợ","north":"đáng sợ"},
  {"sourceRow":148,"standard":"đánh đòn","south":"quánh đòn","central":"đánh đòn","north":"đánh đòn"},
  {"sourceRow":149,"standard":"đánh gió","south":"cạo gió","central":"đánh gió","north":"đánh gió"},
  {"sourceRow":150,"standard":"đánh nhau","south":"đánh lộn","central":"đánh nhau","north":"đánh nhau"},
  {"sourceRow":151,"standard":"đánh thức","south":"kêu dậy","central":"đánh thức","north":"đánh thức"},
  {"sourceRow":152,"standard":"đau đầu","south":"nhức đầu","central":"đau trốc","north":"đau đầu"},
  {"sourceRow":153,"standard":"đắt","south":"mắc","central":"mắc","north":"đắt"},
  {"sourceRow":154,"standard":"đắt đỏ","south":"mắc mỏ","central":"đắt đỏ","north":"đắt đỏ"},
  {"sourceRow":155,"standard":"đắt quá","south":"mắc quá","central":"đắt quá","north":"đắt quá"},
  {"sourceRow":156,"standard":"đâu","south":"đâu","central":"mô","north":"đâu"},
  {"sourceRow":157,"standard":"đầu","south":"đầu","central":"trốc","north":"đầu"},
  {"sourceRow":158,"standard":"đậu cô ve","south":"đậu que","central":"đậu que","north":"đậu cô ve"},
  {"sourceRow":159,"standard":"đầu tóc","south":"đầu tóc","central":"trốc tóc","north":"đầu tóc"},
  {"sourceRow":160,"standard":"đèn pin","south":"đèn bấm","central":"đèn pin","north":"đèn pin"},
  {"sourceRow":161,"standard":"để","south":"đặng","central":"để","north":"để"},
  {"sourceRow":162,"standard":"đến","south":"tới","central":"đến","north":"đến"},
  {"sourceRow":163,"standard":"đến muộn","south":"đến trễ","central":"đến trễ","north":"đến muộn"},
  {"sourceRow":164,"standard":"đi chơi","south":"đi chơi","central":"đi nhởi","north":"đi chơi"},
  {"sourceRow":165,"standard":"đi đâu","south":"đi đâu","central":"đi mô","north":"đi đâu"},
  {"sourceRow":166,"standard":"đi nhờ xe","south":"đi ké xe","central":"đi nhờ xe","north":"đi nhờ xe"},
  {"sourceRow":167,"standard":"đi ở thuê","south":"ở mướn","central":"đi ở thuê","north":"đi ở thuê"},
  {"sourceRow":168,"standard":"đi vào","south":"đi vô","central":"đi vô","north":"đi vào"},
  {"sourceRow":169,"standard":"đi vệ sinh","south":"đi cầu","central":"đi vệ sinh","north":"đi vệ sinh"},
  {"sourceRow":170,"standard":"đi xe nhờ","south":"quá giang","central":"đi xe nhờ","north":"đi xe nhờ"},
  {"sourceRow":171,"standard":"đĩa cơm","south":"dĩa cơm","central":"đĩa cơm","north":"đĩa cơm"},
  {"sourceRow":172,"standard":"điều hòa","south":"máy lạnh","central":"điều hòa","north":"điều hòa"},
  {"sourceRow":173,"standard":"đó","south":"đó","central":"nớ","north":"đó"},
  {"sourceRow":174,"standard":"đoạn đường","south":"khúc đường","central":"đoạn đường","north":"đoạn đường"},
  {"sourceRow":175,"standard":"đón","south":"rước","central":"rước","north":"đón"},
  {"sourceRow":176,"standard":"đỗ","south":"đậu","central":"đỗ","north":"đỗ"},
  {"sourceRow":177,"standard":"đỗ đen","south":"đậu đen","central":"đỗ đen","north":"đỗ đen"},
  {"sourceRow":178,"standard":"đồ giả","south":"đồ dỏm","central":"đồ giả","north":"đồ giả"},
  {"sourceRow":179,"standard":"đỗ tương","south":"đậu nành","central":"đỗ tương","north":"đỗ tương"},
  {"sourceRow":180,"standard":"đỗ xanh","south":"đậu xanh","central":"đỗ xanh","north":"đỗ xanh"},
  {"sourceRow":181,"standard":"đỗ xe","south":"đậu xe","central":"đỗ xe","north":"đỗ xe"},
  {"sourceRow":182,"standard":"đôi khi","south":"lâu lâu","central":"đôi khi","north":"đôi khi"},
  {"sourceRow":183,"standard":"đồng ruộng","south":"đồng ruộng","central":"đồng rọng","north":"đồng ruộng"},
  {"sourceRow":184,"standard":"đùa giỡn","south":"cà rỡn","central":"đùa giỡn","north":"đùa giỡn"},
  {"sourceRow":185,"standard":"đùa nhau","south":"giỡn nhau","central":"đùa nhau","north":"đùa nhau"},
  {"sourceRow":186,"standard":"đúng vậy","south":"đúng vậy","central":"đúng rứa","north":"đúng vậy"},
  {"sourceRow":187,"standard":"đuổi","south":"rượt","central":"đuổi","north":"đuổi"},
  {"sourceRow":188,"standard":"đuổi theo","south":"rượt theo","central":"đuổi theo","north":"đuổi theo"},
  {"sourceRow":189,"standard":"đưa hộ","south":"đưa giùm","central":"đưa hộ","north":"đưa hộ"},
  {"sourceRow":190,"standard":"đừng","south":"đừng","central":"đừng","north":"chớ"},
  {"sourceRow":191,"standard":"đường","south":"đường","central":"đàng","north":"đường"},
  {"sourceRow":192,"standard":"đường đi","south":"đường đi","central":"đàng đi","north":"đường đi"},
  {"sourceRow":193,"standard":"đường làng","south":"đường làng","central":"đàng làng","north":"đường làng"},
  {"sourceRow":194,"standard":"em ấy","south":"ẻm","central":"em ấy","north":"em ấy"},
  {"sourceRow":195,"standard":"gáy","south":"ót","central":"gáy","north":"gáy"},
  {"sourceRow":196,"standard":"gãy","south":"gãy","central":"gãy","north":"gẫy"},
  {"sourceRow":197,"standard":"gần","south":"gần","central":"gưn","north":"gần"},
  {"sourceRow":198,"standard":"gầy","south":"ốm","central":"gầy","north":"gầy"},
  {"sourceRow":199,"standard":"gầy đét","south":"ốm nhách","central":"gầy đét","north":"gầy đét"},
  {"sourceRow":200,"standard":"ghen tị","south":"ganh tị","central":"ghen tị","north":"ghen tị"},
  {"sourceRow":201,"standard":"gì","south":"gì","central":"chi","north":"gì"},
  {"sourceRow":202,"standard":"già","south":"già","central":"tra","north":"già"},
  {"sourceRow":203,"standard":"giá đỗ","south":"giá","central":"giá","north":"giá đỗ"},
  {"sourceRow":204,"standard":"giả vờ","south":"giả bộ","central":"giả vờ","north":"giả vờ"},
  {"sourceRow":205,"standard":"giảm giá","south":"bớt giá","central":"giảm giá","north":"giảm giá"},
  {"sourceRow":206,"standard":"giàu","south":"giàu","central":"giàu","north":"giầu"},
  {"sourceRow":207,"standard":"giẫm","south":"đạp","central":"đạp","north":"giẫm"},
  {"sourceRow":208,"standard":"giật","south":"giựt","central":"giật","north":"giật"},
  {"sourceRow":209,"standard":"giật mình","south":"hết hồn","central":"giật mình","north":"giật mình"},
  {"sourceRow":210,"standard":"giấu","south":"ém","central":"giấu","north":"giấu"},
  {"sourceRow":211,"standard":"giò lụa","south":"chả lụa","central":"chả lụa","north":"giò lụa"},
  {"sourceRow":212,"standard":"giò sống","south":"chả sống","central":"giò sống","north":"giò sống"},
  {"sourceRow":213,"standard":"giờ","south":"giờ","central":"chừ","north":"giờ"},
  {"sourceRow":214,"standard":"giúp","south":"giùm","central":"giúp","north":"giúp"},
  {"sourceRow":215,"standard":"giữa trưa","south":"giữa trưa","central":"giữa trửa","north":"giữa trưa"},
  {"sourceRow":216,"standard":"gọi","south":"kêu","central":"kêu","north":"gọi"},
  {"sourceRow":217,"standard":"gọi tên","south":"kêu tên","central":"gọi tên","north":"gọi tên"},
  {"sourceRow":218,"standard":"gửi","south":"gởi","central":"gửi","north":"gửi"},
  {"sourceRow":219,"standard":"gửi thư","south":"gởi thư","central":"gửi thư","north":"gửi thư"},
  {"sourceRow":220,"standard":"gương","south":"kiếng","central":"gương","north":"gương"},
  {"sourceRow":221,"standard":"hài lòng","south":"ưng bụng","central":"hài lòng","north":"hài lòng"},
  {"sourceRow":222,"standard":"hãm phanh","south":"đạp thắng","central":"hãm phanh","north":"hãm phanh"},
  {"sourceRow":223,"standard":"hành hoa","south":"hành lá","central":"hành lá","north":"hành hoa"},
  {"sourceRow":224,"standard":"hạt điều","south":"đào lộn hột","central":"hạt điều","north":"hạt điều"},
  {"sourceRow":225,"standard":"hắt hơi","south":"nhảy mũi","central":"hắt hơi","north":"hắt hơi"},
  {"sourceRow":226,"standard":"hết sạch","south":"hết ráo","central":"hết sạch","north":"hết sạch"},
  {"sourceRow":227,"standard":"hiệu thuốc","south":"tiệm thuốc","central":"hiệu thuốc","north":"hiệu thuốc"},
  {"sourceRow":228,"standard":"hoa","south":"bông","central":"bông","north":"hoa"},
  {"sourceRow":229,"standard":"hoa dâm bụt","south":"bông bụp","central":"hoa dâm bụt","north":"hoa dâm bụt"},
  {"sourceRow":230,"standard":"hỏi gì","south":"hỏi gì","central":"hỏi chi","north":"hỏi gì"},
  {"sourceRow":231,"standard":"hỏng","south":"hư","central":"hư","north":"hỏng"},
  {"sourceRow":232,"standard":"hỏng rồi","south":"hư rồi","central":"hỏng rồi","north":"hỏng rồi"},
  {"sourceRow":233,"standard":"hổ","south":"cọp","central":"cọp","north":"hổ"},
  {"sourceRow":234,"standard":"hôm ấy","south":"bữa đó","central":"hôm ấy","north":"hôm ấy"},
  {"sourceRow":235,"standard":"hôm nào","south":"bữa nào","central":"bữa mô","north":"hôm nào"},
  {"sourceRow":236,"standard":"hôm nay","south":"hôm nay","central":"bữa ni","north":"hôm nay"},
  {"sourceRow":237,"standard":"hôm qua","south":"hôm qua","central":"bữa qua","north":"hôm qua"},
  {"sourceRow":238,"standard":"hôm sau","south":"bữa sau","central":"hôm sau","north":"hôm sau"},
  {"sourceRow":239,"standard":"hôm trước","south":"bữa trước","central":"hôm trước","north":"hôm trước"},
  {"sourceRow":240,"standard":"hương","south":"nhang","central":"nhang","north":"hương"},
  {"sourceRow":241,"standard":"im lặng","south":"im re","central":"im lặng","north":"im lặng"},
  {"sourceRow":242,"standard":"kẹo lạc","south":"kẹo đậu phộng","central":"kẹo lạc","north":"kẹo lạc"},
  {"sourceRow":243,"standard":"kẹt","south":"mắc","central":"kẹt","north":"kẹt"},
  {"sourceRow":244,"standard":"khập khiễng","south":"cà thọt","central":"khập khiễng","north":"khập khiễng"},
  {"sourceRow":245,"standard":"khoác lác","south":"nói dóc","central":"khoác lác","north":"khoác lác"},
  {"sourceRow":246,"standard":"khỏe","south":"phẻ","central":"khỏe","north":"khỏe"},
  {"sourceRow":247,"standard":"không","south":"hông","central":"nỏ","north":"không"},
  {"sourceRow":248,"standard":"không biết","south":"không biết","central":"không biết","north":"chả biết"},
  {"sourceRow":249,"standard":"không có","south":"không có","central":"không có","north":"chả có"},
  {"sourceRow":250,"standard":"không được","south":"không được","central":"không được","north":"chả được"},
  {"sourceRow":251,"standard":"không may","south":"xui","central":"xui","north":"không may"},
  {"sourceRow":252,"standard":"không sao","south":"hổng sao","central":"không sao","north":"chả sao"},
  {"sourceRow":253,"standard":"không thấy","south":"không thấy","central":"nỏ chộ","north":"không thấy"},
  {"sourceRow":254,"standard":"không thích","south":"không thích","central":"nỏ ưng","north":"không thích"},
  {"sourceRow":255,"standard":"không tìm thấy","south":"kiếm hổng ra","central":"không tìm thấy","north":"không tìm thấy"},
  {"sourceRow":256,"standard":"khuyến mại","south":"khuyến mãi","central":"khuyến mại","north":"khuyến mại"},
  {"sourceRow":257,"standard":"kia","south":"kia","central":"tê","north":"kia"},
  {"sourceRow":258,"standard":"kìa","south":"kìa","central":"tề","north":"kìa"},
  {"sourceRow":259,"standard":"kim cương","south":"hột xoàn","central":"kim cương","north":"kim cương"},
  {"sourceRow":260,"standard":"kính đeo mắt","south":"kiếng đeo mắt","central":"kính đeo mắt","north":"kính đeo mắt"},
  {"sourceRow":261,"standard":"kính râm","south":"kính mát","central":"kính mát","north":"kính râm"},
  {"sourceRow":262,"standard":"kỳ quặc","south":"dị hợm","central":"kỳ quặc","north":"kỳ quặc"},
  {"sourceRow":263,"standard":"la hét","south":"la làng","central":"la hét","north":"la hét"},
  {"sourceRow":264,"standard":"lạc","south":"đậu phộng","central":"đậu phụng","north":"lạc"},
  {"sourceRow":265,"standard":"lạc rang","south":"đậu phộng rang","central":"lạc rang","north":"lạc rang"},
  {"sourceRow":266,"standard":"làm","south":"làm","central":"mần","north":"làm"},
  {"sourceRow":267,"standard":"làm đỏm","south":"làm dáng","central":"làm đỏm","north":"làm đỏm"},
  {"sourceRow":268,"standard":"làm gì","south":"làm gì","central":"làm chi","north":"làm gì"},
  {"sourceRow":269,"standard":"làm hộ","south":"làm giùm","central":"làm hộ","north":"làm hộ"},
  {"sourceRow":270,"standard":"lau","south":"lau","central":"chùi","north":"lau"},
  {"sourceRow":271,"standard":"lấy","south":"lấy","central":"bợ","north":"lấy"},
  {"sourceRow":272,"standard":"lẽ nào","south":"lẽ nào","central":"lẽ nào","north":"nhẽ nào"},
  {"sourceRow":273,"standard":"lọ thủy tinh","south":"hũ thủy tinh","central":"lọ thủy tinh","north":"lọ thủy tinh"},
  {"sourceRow":274,"standard":"lộn xộn","south":"búa xua","central":"lộn xộn","north":"lộn xộn"},
  {"sourceRow":275,"standard":"lông mày","south":"chân mày","central":"lông mày","north":"lông mày"},
  {"sourceRow":276,"standard":"lốp xe","south":"vỏ xe","central":"vỏ xe","north":"lốp xe"},
  {"sourceRow":277,"standard":"lời","south":"lời","central":"lời","north":"nhời"},
  {"sourceRow":278,"standard":"lợn","south":"heo","central":"heo","north":"lợn"},
  {"sourceRow":279,"standard":"lúa","south":"lúa","central":"ló","north":"lúa"},
  {"sourceRow":280,"standard":"lúc ấy","south":"hồi đó","central":"lúc ấy","north":"lúc ấy"},
  {"sourceRow":281,"standard":"lúc nào","south":"lúc nào","central":"khi mô","north":"lúc nào"},
  {"sourceRow":282,"standard":"lừa","south":"gạt","central":"lừa","north":"lừa"},
  {"sourceRow":283,"standard":"lừa gạt","south":"lường gạt","central":"lừa gạt","north":"lừa gạt"},
  {"sourceRow":284,"standard":"lười","south":"làm biếng","central":"lười","north":"lười"},
  {"sourceRow":285,"standard":"mách","south":"méc","central":"mách","north":"mách"},
  {"sourceRow":286,"standard":"mãi","south":"hoài","central":"mãi","north":"mãi"},
  {"sourceRow":287,"standard":"màn","south":"mùng","central":"mùng","north":"màn"},
  {"sourceRow":288,"standard":"mang","south":"rinh","central":"mang","north":"mang"},
  {"sourceRow":289,"standard":"mang ra","south":"đem ra","central":"mang ra","north":"mang ra"},
  {"sourceRow":290,"standard":"mang thai","south":"có bầu","central":"mang thai","north":"mang thai"},
  {"sourceRow":291,"standard":"mang vào","south":"đem vô","central":"mang vào","north":"mang vào"},
  {"sourceRow":292,"standard":"mạnh khỏe","south":"mạnh giỏi","central":"mạnh khỏe","north":"mạnh khỏe"},
  {"sourceRow":293,"standard":"màu","south":"màu","central":"màu","north":"mầu"},
  {"sourceRow":294,"standard":"mày","south":"mày","central":"mi","north":"mày"},
  {"sourceRow":295,"standard":"máy ảnh","south":"máy chụp hình","central":"máy ảnh","north":"máy ảnh"},
  {"sourceRow":296,"standard":"may mắn","south":"hên","central":"hên","north":"may mắn"},
  {"sourceRow":297,"standard":"mặc cả","south":"trả giá","central":"mặc cả","north":"mặc cả"},
  {"sourceRow":298,"standard":"mặc kệ","south":"thây kệ","central":"mặc kệ","north":"mặc kệ"},
  {"sourceRow":299,"standard":"mắng","south":"la","central":"mắng","north":"mắng"},
  {"sourceRow":300,"standard":"mắng mỏ","south":"rầy la","central":"mắng mỏ","north":"mắng mỏ"},
  {"sourceRow":301,"standard":"mắng nhau","south":"rầy nhau","central":"mắng nhau","north":"mắng nhau"},
  {"sourceRow":302,"standard":"mất điện","south":"cúp điện","central":"cúp điện","north":"mất điện"},
  {"sourceRow":303,"standard":"mất hẳn","south":"mất tiêu","central":"mất hẳn","north":"mất hẳn"},
  {"sourceRow":304,"standard":"mất rồi","south":"mất tiêu rồi","central":"mất rồi","north":"mất rồi"},
  {"sourceRow":305,"standard":"mấy hôm","south":"mấy bữa","central":"mấy hôm","north":"mấy hôm"},
  {"sourceRow":306,"standard":"mẹ","south":"má","central":"mạ","north":"u"},
  {"sourceRow":307,"standard":"miến","south":"bún tàu","central":"miến","north":"miến"},
  {"sourceRow":308,"standard":"mình","south":"mình","central":"miềng","north":"mình"},
  {"sourceRow":309,"standard":"mọi người","south":"bà con","central":"mọi người","north":"mọi người"},
  {"sourceRow":310,"standard":"mộc nhĩ","south":"nấm mèo","central":"mộc nhĩ","north":"mộc nhĩ"},
  {"sourceRow":311,"standard":"một chiếc bánh mì","south":"một ổ bánh mì","central":"một chiếc bánh mì","north":"một chiếc bánh mì"},
  {"sourceRow":312,"standard":"một chút","south":"một xíu","central":"một chút","north":"một chút"},
  {"sourceRow":313,"standard":"một lát","south":"một hồi","central":"một lát","north":"một lát"},
  {"sourceRow":314,"standard":"một mình","south":"mình ên","central":"một mình","north":"một mình"},
  {"sourceRow":315,"standard":"mũ","south":"nón","central":"nón","north":"mũ"},
  {"sourceRow":316,"standard":"mua chịu","south":"mua thiếu","central":"mua chịu","north":"mua chịu"},
  {"sourceRow":317,"standard":"mua gì","south":"mua gì","central":"mua chi","north":"mua gì"},
  {"sourceRow":318,"standard":"mua hộ","south":"mua giùm","central":"mua hộ","north":"mua hộ"},
  {"sourceRow":319,"standard":"mùi tàu","south":"ngò gai","central":"mùi tàu","north":"mùi tàu"},
  {"sourceRow":320,"standard":"mụn nhọt","south":"mụt nhọt","central":"mụn nhọt","north":"mụn nhọt"},
  {"sourceRow":321,"standard":"muôi","south":"vá","central":"muôi","north":"muôi"},
  {"sourceRow":322,"standard":"muôi canh","south":"vá canh","central":"muôi canh","north":"muôi canh"},
  {"sourceRow":323,"standard":"muộn","south":"trễ","central":"trễ","north":"muộn"},
  {"sourceRow":324,"standard":"mừng tuổi","south":"lì xì","central":"mừng tuổi","north":"mừng tuổi"},
  {"sourceRow":325,"standard":"mượn tạm","south":"mượn đỡ","central":"mượn tạm","north":"mượn tạm"},
  {"sourceRow":326,"standard":"mướp đắng","south":"khổ qua","central":"khổ qua","north":"mướp đắng"},
  {"sourceRow":327,"standard":"mướp đắng xào","south":"khổ qua xào","central":"mướp đắng xào","north":"mướp đắng xào"},
  {"sourceRow":328,"standard":"na","south":"mãng cầu","central":"mãng cầu","north":"na"},
  {"sourceRow":329,"standard":"này","south":"nè","central":"ni","north":"này"},
  {"sourceRow":330,"standard":"nằm sấp","south":"nằm úp","central":"nằm sấp","north":"nằm sấp"},
  {"sourceRow":331,"standard":"nấp","south":"núp","central":"nấp","north":"nấp"},
  {"sourceRow":332,"standard":"ném","south":"quăng","central":"ném","north":"ném"},
  {"sourceRow":333,"standard":"nem rán","south":"chả giò","central":"ram","north":"nem rán"},
  {"sourceRow":334,"standard":"nến","south":"đèn cầy","central":"nến","north":"nến"},
  {"sourceRow":335,"standard":"ngã","south":"té","central":"bổ","north":"ngã"},
  {"sourceRow":336,"standard":"ngan","south":"vịt xiêm","central":"vịt xiêm","north":"ngan"},
  {"sourceRow":337,"standard":"ngán","south":"ớn","central":"ngán","north":"ngán"},
  {"sourceRow":338,"standard":"ngạt","south":"ngộp","central":"ngạt","north":"ngạt"},
  {"sourceRow":339,"standard":"ngay","south":"liền","central":"ngay","north":"ngay"},
  {"sourceRow":340,"standard":"ngấy","south":"ớn","central":"ngấy","north":"ngấy"},
  {"sourceRow":341,"standard":"nghiện","south":"ghiền","central":"nghiện","north":"nghiện"},
  {"sourceRow":342,"standard":"nghiền","south":"ghiền","central":"nghiền","north":"nghiền"},
  {"sourceRow":343,"standard":"nghìn","south":"ngàn","central":"nghìn","north":"nghìn"},
  {"sourceRow":344,"standard":"ngõ","south":"hẻm","central":"kiệt","north":"ngõ"},
  {"sourceRow":345,"standard":"ngõ nhỏ","south":"hẻm nhỏ","central":"ngõ nhỏ","north":"ngõ nhỏ"},
  {"sourceRow":346,"standard":"ngoài ấy","south":"ngoải","central":"ngoài ấy","north":"ngoài ấy"},
  {"sourceRow":347,"standard":"ngoài sân","south":"ngoài sân","central":"ngoài cươi","north":"ngoài sân"},
  {"sourceRow":348,"standard":"ngô","south":"bắp","central":"bắp","north":"ngô"},
  {"sourceRow":349,"standard":"ngô luộc","south":"bắp luộc","central":"ngô luộc","north":"ngô luộc"},
  {"sourceRow":350,"standard":"ngô nướng","south":"bắp nướng","central":"ngô nướng","north":"ngô nướng"},
  {"sourceRow":351,"standard":"ngồi xổm","south":"ngồi chồm hỗm","central":"ngồi chồm hỗm","north":"ngồi xổm"},
  {"sourceRow":352,"standard":"người yêu","south":"bồ","central":"người yêu","north":"người yêu"},
  {"sourceRow":353,"standard":"ngượng","south":"mắc cỡ","central":"ngượng","north":"ngượng"},
  {"sourceRow":354,"standard":"nhà tầng","south":"nhà lầu","central":"nhà tầng","north":"nhà tầng"},
  {"sourceRow":355,"standard":"nhà vệ sinh","south":"nhà cầu","central":"nhà vệ sinh","north":"nhà vệ sinh"},
  {"sourceRow":356,"standard":"nhại","south":"nhái","central":"nhại","north":"nhại"},
  {"sourceRow":357,"standard":"nhanh","south":"lẹ","central":"lẹ","north":"nhanh"},
  {"sourceRow":358,"standard":"nhanh lên","south":"lẹ lên","central":"nhanh lên","north":"nhanh lên"},
  {"sourceRow":359,"standard":"nhảy","south":"nhảy","central":"nhảy","north":"nhẩy"},
  {"sourceRow":360,"standard":"nhăm nhe","south":"lăm le","central":"nhăm nhe","north":"nhăm nhe"},
  {"sourceRow":361,"standard":"nhặt","south":"lượm","central":"lặt","north":"nhặt"},
  {"sourceRow":362,"standard":"nhặt lên","south":"lượm lên","central":"nhặt lên","north":"nhặt lên"},
  {"sourceRow":363,"standard":"nhầm","south":"lộn","central":"nhầm","north":"nhầm"},
  {"sourceRow":364,"standard":"nhẫn","south":"cà rá","central":"nhẫn","north":"nhẫn"},
  {"sourceRow":365,"standard":"nhân đức","south":"nhơn đức","central":"nhân đức","north":"nhân đức"},
  {"sourceRow":366,"standard":"nhất","south":"nhứt","central":"nhất","north":"nhất"},
  {"sourceRow":367,"standard":"nhé","south":"nha","central":"nhé","north":"nhá"},
  {"sourceRow":368,"standard":"nhỉ","south":"nhỉ","central":"hè","north":"nhở"},
  {"sourceRow":369,"standard":"nhìn","south":"nhìn","central":"ngó","north":"nom"},
  {"sourceRow":370,"standard":"nhìn thấy","south":"nhìn thấy","central":"chộ","north":"nhìn thấy"},
  {"sourceRow":371,"standard":"nhìn xem","south":"coi thử","central":"nhìn xem","north":"nom xem"},
  {"sourceRow":372,"standard":"nhỡ","south":"lỡ","central":"nhỡ","north":"nhỡ"},
  {"sourceRow":373,"standard":"như vậy","south":"như vậy","central":"như rứa","north":"như vậy"},
  {"sourceRow":374,"standard":"nó","south":"nó","central":"hắn","north":"nó"},
  {"sourceRow":375,"standard":"nói ba hoa","south":"nói ba láp","central":"nói ba hoa","north":"nói ba hoa"},
  {"sourceRow":376,"standard":"nói dối","south":"nói xạo","central":"nói dối","north":"nói dối"},
  {"sourceRow":377,"standard":"nói gì","south":"nói gì","central":"nói chi","north":"nói gì"},
  {"sourceRow":378,"standard":"nói phét","south":"nói xạo","central":"nói láp","north":"nói phét"},
  {"sourceRow":379,"standard":"nóng tính","south":"nóng tánh","central":"nóng tính","north":"nóng tính"},
  {"sourceRow":380,"standard":"nồi đất","south":"cái tộ","central":"nồi đất","north":"nồi đất"},
  {"sourceRow":381,"standard":"nôn","south":"ói","central":"nôn","north":"mửa"},
  {"sourceRow":382,"standard":"nữa","south":"nữa","central":"nựa","north":"nữa"},
  {"sourceRow":383,"standard":"nước","south":"nước","central":"nác","north":"nước"},
  {"sourceRow":384,"standard":"nước bọt","south":"nước miếng","central":"nước bọt","north":"nước dãi"},
  {"sourceRow":385,"standard":"nước dùng","south":"nước lèo","central":"nước dùng","north":"nước dùng"},
  {"sourceRow":386,"standard":"nước hoa","south":"dầu thơm","central":"nước hoa","north":"nước hoa"},
  {"sourceRow":387,"standard":"nước mưa","south":"nước mưa","central":"nác mưa","north":"nước mưa"},
  {"sourceRow":388,"standard":"nước sôi","south":"nước sôi","central":"nác sôi","north":"nước sôi"},
  {"sourceRow":389,"standard":"nước uống","south":"nước uống","central":"nác uống","north":"nước uống"},
  {"sourceRow":390,"standard":"nướng","south":"nướng","central":"náng","north":"nướng"},
  {"sourceRow":391,"standard":"ô","south":"dù","central":"dù","north":"ô"},
  {"sourceRow":392,"standard":"ô tô","south":"xe hơi","central":"xe hơi","north":"ô tô"},
  {"sourceRow":393,"standard":"ốm","south":"bệnh","central":"đau","north":"ốm"},
  {"sourceRow":394,"standard":"ốm đau","south":"đau bịnh","central":"ốm đau","north":"ốm đau"},
  {"sourceRow":395,"standard":"ông ấy","south":"ổng","central":"ông ấy","north":"ông ấy"},
  {"sourceRow":396,"standard":"ở đâu","south":"ở đâu","central":"ở mô","north":"ở đâu"},
  {"sourceRow":397,"standard":"ở đây","south":"ở đây","central":"ở ni","north":"ở đây"},
  {"sourceRow":398,"standard":"ở kia","south":"ở kia","central":"ở tê","north":"ở kia"},
  {"sourceRow":399,"standard":"ở ngoài","south":"ở ngoải","central":"ở ngoài","north":"ở ngoài"},
  {"sourceRow":400,"standard":"ở trên","south":"ở trển","central":"ở trên","north":"ở trên"},
  {"sourceRow":401,"standard":"ở trong","south":"ở trỏng","central":"ở trong","north":"ở trong"},
  {"sourceRow":402,"standard":"phá phách","south":"quậy phá","central":"phá phách","north":"phá phách"},
  {"sourceRow":403,"standard":"phanh","south":"thắng","central":"thắng","north":"phanh"},
  {"sourceRow":404,"standard":"phanh xe","south":"thắng xe","central":"phanh xe","north":"phanh xe"},
  {"sourceRow":405,"standard":"phích nước","south":"bình thủy","central":"phích nước","north":"phích nước"},
  {"sourceRow":406,"standard":"phong bì","south":"bao thư","central":"bao thư","north":"phong bì"},
  {"sourceRow":407,"standard":"phô mai","south":"phô mai","central":"phô mai","north":"phó mát"},
  {"sourceRow":408,"standard":"phụ xe","south":"lơ xe","central":"phụ xe","north":"phụ xe"},
  {"sourceRow":409,"standard":"phúc","south":"phước","central":"phúc","north":"phúc"},
  {"sourceRow":410,"standard":"phượng","south":"phụng","central":"phượng","north":"phượng"},
  {"sourceRow":411,"standard":"quả","south":"trái","central":"trái","north":"quả"},
  {"sourceRow":412,"standard":"quả bóng","south":"trái banh","central":"trái banh","north":"quả bóng"},
  {"sourceRow":413,"standard":"quả bóng đá","south":"trái banh","central":"quả bóng đá","north":"quả bóng đá"},
  {"sourceRow":414,"standard":"quả cà chua","south":"trái cà chua","central":"quả cà chua","north":"quả cà chua"},
  {"sourceRow":415,"standard":"quả cam","south":"trái cam","central":"quả cam","north":"quả cam"},
  {"sourceRow":416,"standard":"quả chanh","south":"trái chanh","central":"quả chanh","north":"quả chanh"},
  {"sourceRow":417,"standard":"quả chuối","south":"trái chuối","central":"quả chuối","north":"quả chuối"},
  {"sourceRow":418,"standard":"quả dứa","south":"trái thơm","central":"quả dứa","north":"quả dứa"},
  {"sourceRow":419,"standard":"quả dừa","south":"trái dừa","central":"quả dừa","north":"quả dừa"},
  {"sourceRow":420,"standard":"quả dưa hấu","south":"trái dưa hấu","central":"quả dưa hấu","north":"quả dưa hấu"},
  {"sourceRow":421,"standard":"quả na","south":"trái mãng cầu","central":"quả na","north":"quả na"},
  {"sourceRow":422,"standard":"quả ổi","south":"trái ổi","central":"quả ổi","north":"quả ổi"},
  {"sourceRow":423,"standard":"quả ớt","south":"trái ớt","central":"quả ớt","north":"quả ớt"},
  {"sourceRow":424,"standard":"quả quất","south":"trái tắc","central":"quả quất","north":"quả quất"},
  {"sourceRow":425,"standard":"quả roi","south":"trái mận","central":"quả roi","north":"quả roi"},
  {"sourceRow":426,"standard":"quả táo","south":"trái táo","central":"quả táo","north":"quả táo"},
  {"sourceRow":427,"standard":"quả xoài","south":"trái xoài","central":"quả xoài","north":"quả xoài"},
  {"sourceRow":428,"standard":"quan tài","south":"hòm","central":"hòm","north":"quan tài"},
  {"sourceRow":429,"standard":"quần đùi","south":"quần xà lỏn","central":"quần đùi","north":"quần đùi"},
  {"sourceRow":430,"standard":"quất","south":"tắc","central":"quất","north":"quất"},
  {"sourceRow":431,"standard":"quên mất","south":"quên mất tiêu","central":"quên mất","north":"quên mất"},
  {"sourceRow":432,"standard":"rán","south":"chiên","central":"rán","north":"rán"},
  {"sourceRow":433,"standard":"rảnh","south":"rảnh","central":"rảnh","north":"rỗi"},
  {"sourceRow":434,"standard":"ranh mãnh","south":"ma lanh","central":"ranh mãnh","north":"ranh mãnh"},
  {"sourceRow":435,"standard":"rau cải cúc","south":"rau tần ô","central":"rau cải cúc","north":"rau cải cúc"},
  {"sourceRow":436,"standard":"rau mùi","south":"ngò rí","central":"ngò","north":"rau mùi"},
  {"sourceRow":437,"standard":"rau mùi tàu","south":"rau ngò gai","central":"rau mùi tàu","north":"rau mùi tàu"},
  {"sourceRow":438,"standard":"rất dở","south":"dở ẹc","central":"rất dở","north":"rất dở"},
  {"sourceRow":439,"standard":"rẽ","south":"quẹo","central":"quẹo","north":"rẽ"},
  {"sourceRow":440,"standard":"rẻ bèo","south":"rẻ rề","central":"rẻ bèo","north":"rẻ bèo"},
  {"sourceRow":441,"standard":"rèm","south":"màn cửa","central":"màn cửa","north":"rèm"},
  {"sourceRow":442,"standard":"rét buốt","south":"lạnh cóng","central":"rét buốt","north":"rét buốt"},
  {"sourceRow":443,"standard":"rết","south":"rít","central":"rết","north":"rết"},
  {"sourceRow":444,"standard":"rồi","south":"rầu","central":"rồi","north":"rồi"},
  {"sourceRow":445,"standard":"ruốc thịt","south":"chà bông","central":"ruốc thịt","north":"ruốc thịt"},
  {"sourceRow":446,"standard":"ruộng","south":"ruộng","central":"rọng","north":"ruộng"},
  {"sourceRow":447,"standard":"ruộng lúa","south":"ruộng lúa","central":"rọng ló","north":"ruộng lúa"},
  {"sourceRow":448,"standard":"ruột","south":"ruột","central":"rọt","north":"ruột"},
  {"sourceRow":449,"standard":"rừng","south":"rừng","central":"rú","north":"rừng"},
  {"sourceRow":450,"standard":"sai","south":"trật","central":"sai","north":"sai"},
  {"sourceRow":451,"standard":"sáng nay","south":"sáng nay","central":"sáng ni","north":"sáng nay"},
  {"sourceRow":452,"standard":"sao","south":"sao","central":"răng","north":"sao"},
  {"sourceRow":453,"standard":"sao thế","south":"sao thế","central":"răng rứa","north":"sao thế"},
  {"sourceRow":454,"standard":"sau này","south":"mai mốt","central":"sau này","north":"sau này"},
  {"sourceRow":455,"standard":"sắc","south":"bén","central":"sắc","north":"sắc"},
  {"sourceRow":456,"standard":"săm xe","south":"ruột xe","central":"săm xe","north":"săm xe"},
  {"sourceRow":457,"standard":"sắn","south":"khoai mì","central":"sắn","north":"sắn"},
  {"sourceRow":458,"standard":"sân","south":"sân","central":"cươi","north":"sân"},
  {"sourceRow":459,"standard":"sân bóng","south":"sân banh","central":"sân bóng","north":"sân bóng"},
  {"sourceRow":460,"standard":"sầy da","south":"trầy da","central":"sầy da","north":"sầy da"},
  {"sourceRow":461,"standard":"sẻ bớt","south":"sớt bớt","central":"sẻ bớt","north":"sẻ bớt"},
  {"sourceRow":462,"standard":"sẹo","south":"thẹo","central":"sẹo","north":"sẹo"},
  {"sourceRow":463,"standard":"sinh con","south":"sanh con","central":"sinh con","north":"sinh con"},
  {"sourceRow":464,"standard":"sôi tiết","south":"sôi máu","central":"sôi tiết","north":"sôi tiết"},
  {"sourceRow":465,"standard":"sợ","south":"ớn","central":"hại","north":"sợ"},
  {"sourceRow":466,"standard":"sởn tóc gáy","south":"rợn tóc gáy","central":"sởn tóc gáy","north":"sởn tóc gáy"},
  {"sourceRow":467,"standard":"súng cao su","south":"ná thun","central":"súng cao su","north":"súng cao su"},
  {"sourceRow":468,"standard":"súp lơ","south":"bông cải","central":"bông cải","north":"súp lơ"},
  {"sourceRow":469,"standard":"súp lơ xanh","south":"bông cải xanh","central":"bông cải xanh","north":"súp lơ xanh"},
  {"sourceRow":470,"standard":"suýt nữa","south":"chút nữa","central":"suýt nữa","north":"tí nữa"},
  {"sourceRow":471,"standard":"sướng","south":"khoái","central":"sướng","north":"sướng"},
  {"sourceRow":472,"standard":"tại sao","south":"tại sao","central":"tại răng","north":"tại sao"},
  {"sourceRow":473,"standard":"tán gẫu","south":"tán dóc","central":"tán gẫu","north":"buôn chuyện"},
  {"sourceRow":474,"standard":"táo","south":"bôm","central":"táo","north":"táo"},
  {"sourceRow":475,"standard":"tao","south":"tao","central":"tau","north":"tao"},
  {"sourceRow":476,"standard":"tàu","south":"tàu","central":"tàu","north":"tầu"},
  {"sourceRow":477,"standard":"tàu hỏa","south":"xe lửa","central":"xe lửa","north":"tàu hỏa"},
  {"sourceRow":478,"standard":"tắc đường","south":"kẹt xe","central":"tắc đường","north":"tắc đường"},
  {"sourceRow":479,"standard":"tận","south":"tuốt","central":"tận","north":"tận"},
  {"sourceRow":480,"standard":"tầng","south":"lầu","central":"tầng","north":"tầng"},
  {"sourceRow":481,"standard":"tầng một","south":"tầng trệt","central":"tầng một","north":"tầng một"},
  {"sourceRow":482,"standard":"tất","south":"vớ","central":"vớ","north":"tất"},
  {"sourceRow":483,"standard":"tẩy bút chì","south":"cục gôm","central":"tẩy bút chì","north":"tẩy bút chì"},
  {"sourceRow":484,"standard":"thạch sùng","south":"thằn lằn","central":"thằn lằn","north":"thạch sùng"},
  {"sourceRow":485,"standard":"thanh toán","south":"tính tiền","central":"trả tiền","north":"thanh toán"},
  {"sourceRow":486,"standard":"thảo nào","south":"hèn chi","central":"thảo nào","north":"bảo sao"},
  {"sourceRow":487,"standard":"thằn lằn","south":"rắn mối","central":"rắn mối","north":"thằn lằn"},
  {"sourceRow":488,"standard":"thắt lưng","south":"dây nịt","central":"thắt lưng","north":"dây lưng"},
  {"sourceRow":489,"standard":"thật","south":"thiệt","central":"thật","north":"thật"},
  {"sourceRow":490,"standard":"thật thà","south":"thiệt thà","central":"thật thà","north":"thật thà"},
  {"sourceRow":491,"standard":"thấy","south":"thấy","central":"chộ","north":"thấy"},
  {"sourceRow":492,"standard":"thèm","south":"thèm","central":"sèm","north":"thèm"},
  {"sourceRow":493,"standard":"thế nào","south":"thế nào","central":"răng rứa","north":"thế nào"},
  {"sourceRow":494,"standard":"thi trượt","south":"thi rớt","central":"thi trượt","north":"thi trượt"},
  {"sourceRow":495,"standard":"thìa","south":"muỗng","central":"muỗng","north":"thìa"},
  {"sourceRow":496,"standard":"thìa cà phê","south":"muỗng cà phê","central":"thìa cà phê","north":"thìa cà phê"},
  {"sourceRow":497,"standard":"thìa canh","south":"muỗng canh","central":"thìa canh","north":"thìa canh"},
  {"sourceRow":498,"standard":"thích","south":"khoái","central":"ưng","north":"thích"},
  {"sourceRow":499,"standard":"thịt ba chỉ","south":"thịt ba rọi","central":"thịt ba chỉ","north":"thịt ba chỉ"},
  {"sourceRow":500,"standard":"thịt lợn","south":"thịt heo","central":"thịt lợn","north":"thịt lợn"},
  {"sourceRow":501,"standard":"thóc","south":"lúa","central":"ló","north":"thóc"},
  {"sourceRow":502,"standard":"thối","south":"thúi","central":"thối","north":"thối"},
  {"sourceRow":503,"standard":"thôi","south":"thâu","central":"thôi","north":"thôi"},
  {"sourceRow":504,"standard":"thuê","south":"mướn","central":"mướn","north":"thuê"},
  {"sourceRow":505,"standard":"thủng","south":"lủng","central":"thủng","north":"thủng"},
  {"sourceRow":506,"standard":"thùng rác","south":"sọt rác","central":"thùng rác","north":"thùng rác"},
  {"sourceRow":507,"standard":"thuyền","south":"ghe","central":"ghe","north":"thuyền"},
  {"sourceRow":508,"standard":"thử xem","south":"thử coi","central":"thử xem","north":"thử xem"},
  {"sourceRow":509,"standard":"thừa","south":"dư","central":"dư","north":"thừa"},
  {"sourceRow":510,"standard":"tiếc","south":"uổng","central":"tiếc","north":"tiếc"},
  {"sourceRow":511,"standard":"tiếc quá","south":"uổng quá","central":"tiếc quá","north":"tiếc quá"},
  {"sourceRow":512,"standard":"tiêm phòng","south":"chích ngừa","central":"tiêm phòng","north":"tiêm phòng"},
  {"sourceRow":513,"standard":"tiêm thuốc","south":"chích thuốc","central":"tiêm thuốc","north":"tiêm thuốc"},
  {"sourceRow":514,"standard":"tìm","south":"kiếm","central":"tìm","north":"tìm"},
  {"sourceRow":515,"standard":"tìm lại","south":"kiếm lại","central":"tìm lại","north":"tìm lại"},
  {"sourceRow":516,"standard":"tính nết","south":"tánh nết","central":"tính nết","north":"tính nết"},
  {"sourceRow":517,"standard":"to","south":"bự","central":"to","north":"to"},
  {"sourceRow":518,"standard":"tôi","south":"tui","central":"tui","north":"tôi"},
  {"sourceRow":519,"standard":"tối nay","south":"tối nay","central":"túi ni","north":"tối nay"},
  {"sourceRow":520,"standard":"tốn kém","south":"hao tốn","central":"tốn kém","north":"tốn kém"},
  {"sourceRow":521,"standard":"trà","south":"trà","central":"trà","north":"chè"},
  {"sourceRow":522,"standard":"trà đặc","south":"trà đậm","central":"trà đặc","north":"trà đặc"},
  {"sourceRow":523,"standard":"trả lại tiền","south":"thối lại tiền","central":"trả lại tiền","north":"trả lại tiền"},
  {"sourceRow":524,"standard":"trái","south":"trái","central":"trấy","north":"trái"},
  {"sourceRow":525,"standard":"trai","south":"trai","central":"trai","north":"giai"},
  {"sourceRow":526,"standard":"tránh","south":"né","central":"tránh","north":"tránh"},
  {"sourceRow":527,"standard":"trâu","south":"trâu","central":"tru","north":"trâu"},
  {"sourceRow":528,"standard":"trầy xước","south":"trầy da","central":"trầy xước","north":"trầy xước"},
  {"sourceRow":529,"standard":"trên ấy","south":"trển","central":"trên ấy","north":"trên ấy"},
  {"sourceRow":530,"standard":"trên cây","south":"trên cây","central":"trên cơn","north":"trên cây"},
  {"sourceRow":531,"standard":"trên đầu","south":"trên đầu","central":"côi trốc","north":"trên đầu"},
  {"sourceRow":532,"standard":"trên đường","south":"trên đường","central":"trên đàng","north":"trên đường"},
  {"sourceRow":533,"standard":"trêu","south":"chọc","central":"trêu","north":"trêu"},
  {"sourceRow":534,"standard":"trong ấy","south":"trỏng","central":"trong ấy","north":"trong ấy"},
  {"sourceRow":535,"standard":"trong rừng","south":"trong rừng","central":"trong rú","north":"trong rừng"},
  {"sourceRow":536,"standard":"trong sân","south":"trong sân","central":"trong cươi","north":"trong sân"},
  {"sourceRow":537,"standard":"trốn","south":"núp","central":"trốn","north":"trốn"},
  {"sourceRow":538,"standard":"trông chừng","south":"coi chừng","central":"trông chừng","north":"trông chừng"},
  {"sourceRow":539,"standard":"trông em","south":"coi em","central":"trông em","north":"trông em"},
  {"sourceRow":540,"standard":"trời","south":"trời","central":"trời","north":"giời"},
  {"sourceRow":541,"standard":"trứng gà","south":"hột gà","central":"trứng gà","north":"trứng gà"},
  {"sourceRow":542,"standard":"túi nhựa","south":"bịch ni-lông","central":"túi nhựa","north":"túi nhựa"},
  {"sourceRow":543,"standard":"túi ni-lông","south":"bịch ni-lông","central":"túi ni-lông","north":"túi ni-lông"},
  {"sourceRow":544,"standard":"túi xách","south":"giỏ xách","central":"túi xách","north":"túi xách"},
  {"sourceRow":545,"standard":"từ nay","south":"từ rày","central":"từ nay","north":"từ nay"},
  {"sourceRow":546,"standard":"uống gì","south":"uống gì","central":"uống chi","north":"uống gì"},
  {"sourceRow":547,"standard":"ưng ý","south":"ưng ý","central":"ưng bụng","north":"ưng ý"},
  {"sourceRow":548,"standard":"va phải","south":"đụng phải","central":"va phải","north":"va phải"},
  {"sourceRow":549,"standard":"vào","south":"vô","central":"vô","north":"vào"},
  {"sourceRow":550,"standard":"vào rừng","south":"vào rừng","central":"vô rú","north":"vào rừng"},
  {"sourceRow":551,"standard":"váy","south":"đầm","central":"váy","north":"váy"},
  {"sourceRow":552,"standard":"vâng","south":"dạ","central":"vâng","north":"vâng"},
  {"sourceRow":553,"standard":"vậy","south":"vậy","central":"rứa","north":"thế"},
  {"sourceRow":554,"standard":"véo","south":"nhéo","central":"véo","north":"véo"},
  {"sourceRow":555,"standard":"về","south":"dìa","central":"về","north":"về"},
  {"sourceRow":556,"standard":"ví","south":"bóp","central":"ví","north":"ví"},
  {"sourceRow":557,"standard":"ví dụ","south":"thí dụ","central":"ví dụ","north":"ví dụ"},
  {"sourceRow":558,"standard":"ví tiền","south":"bóp tiền","central":"ví tiền","north":"ví tiền"},
  {"sourceRow":559,"standard":"vỡ","south":"bể","central":"bể","north":"vỡ"},
  {"sourceRow":560,"standard":"vỡ tan","south":"bể tan","central":"vỡ tan","north":"vỡ tan"},
  {"sourceRow":561,"standard":"vớ vẩn","south":"tào lao","central":"vớ vẩn","north":"linh tinh"},
  {"sourceRow":562,"standard":"vui","south":"vui","central":"bui","north":"vui"},
  {"sourceRow":563,"standard":"vừng","south":"mè","central":"mè","north":"vừng"},
  {"sourceRow":564,"standard":"vừng rang","south":"mè rang","central":"vừng rang","north":"vừng rang"},
  {"sourceRow":565,"standard":"vướng","south":"mắc","central":"vướng","north":"vướng"},
  {"sourceRow":566,"standard":"vứt đi","south":"quăng đi","central":"vứt đi","north":"vứt đi"},
  {"sourceRow":567,"standard":"xa","south":"xa","central":"ngái","north":"xa"},
  {"sourceRow":568,"standard":"xà phòng","south":"xà bông","central":"xà bông","north":"xà phòng"},
  {"sourceRow":569,"standard":"xấu hổ","south":"mắc cỡ","central":"ốt dột","north":"ngượng"},
  {"sourceRow":570,"standard":"xe máy","south":"xe gắn máy","central":"xe máy","north":"xe máy"},
  {"sourceRow":571,"standard":"xem","south":"coi","central":"coi","north":"xem"},
  {"sourceRow":572,"standard":"xem ảnh","south":"coi hình","central":"xem ảnh","north":"xem ảnh"},
  {"sourceRow":573,"standard":"xem phim","south":"coi phim","central":"xem phim","north":"xem phim"},
  {"sourceRow":574,"standard":"xích","south":"sên","central":"xích","north":"xích"},
  {"sourceRow":575,"standard":"xôi lạc","south":"xôi đậu phộng","central":"xôi lạc","north":"xôi lạc"},
] as const;
